### ISSUE TITLE
Опечатки в русской локализации

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#1]
1. поля. опечатка.
![1](https://user-images.githubusercontent.com/3432048/137891638-2c09aae6-f863-4a93-8925-358cda7895e2.png)
нужно: Генерируется из заголовка

2. опечатка

![2](https://user-images.githubusercontent.com/3432048/137891950-dad6864e-d310-47cc-9bb9-ecbc4d7f0f37.jpg)

3.

**Comment by Sulpher** [comment]
Расчитывать цены категории
правильно так:

Рас**с**читывать цены категории

**Comment by Sulpher** [comment]
Trigger JavaScript
лучше так: JavaScript Trigger

**Comment by Sulpher** [comment]
<img width="497" alt="Снимок экрана 2021-10-19 в 14 43 29" src="https://user-images.githubusercontent.com/3432048/137902584-f8f02cde-b02f-4a23-8d60-a9089a8c63a5.png">

здесь можно пояснить, что речь идет о конкретно выбранной категории. или перефразировать или сделать подсказку.

**Comment by Sulpher** [comment]
Учёт кол-ва предлагаю переименовать на: Учёт кол-ва товаров на складе

**Comment by Septdir** [comment]
Сделано
