### ISSUE TITLE
Корзина. Цвет элемента, если нет скидки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#10]
Взгляните:
<img width="319" alt="Снимок экрана 2021-10-19 в 14 19 16" src="https://user-images.githubusercontent.com/3432048/137899465-fb497f09-f48f-42fc-b7e9-90fe481676f1.png">

красный цвет строчки: скидка обращает на себя внимание и юзер сразу смотрит туда. 
а скидки нет. лишнее действие и отвлекает его.
предлагаю сделать проверку: если скидки нет, то не выводить эту строку.

**Comment by Septdir** [comment]
Скидка может динамически появляться и исчезать. Так что скрытие можно сделать в своем custom js использовав событие
`document.addEventListener('onRadicalMartCartAfterUpdateDisplayData', (event) => {});`

Красный цвет убрал
