### ISSUE TITLE
Нехватает единиц измерения

### ISSUE THREAD

**Issue by Georgiy163** [RadicalMart/Bug-Tracker#101]
Комл. или "к-т"

**Comment by progreccor** [comment]
а чем это отличается от штук?

**Comment by Georgiy163** [comment]
> а чем это отличается от штук?

Тем что есть товар состоящий из нескольких коробок например сплит-система из двух коробок и их как то лучше комплектом называть
Конечно есть тут не разбериха учёт ведётся в последнее время раздельно но для продажи витрины это не вариант

**Comment by Georgiy163** [comment]
Идеально это конечно когда клиент выбирает товар а программа сама собирает комплект но это я даже представить сейфу не могу как это реализовать в интернет-магазинах

**Comment by Georgiy163** [comment]
В счёте выставляем как комплект а в накладной уже раздельно штуки но и то не всегда бывает и поставщик комплектом отгружают

**Comment by Georgiy163** [comment]
Кстати носки например то же лучше наверное пара называть, хотя в одежде я не понимаю

**Comment by progreccor** [comment]
носки продаются так: 
"трикотажные носки, 1 пара" - 1шт
то что у вас
"комплект кондиционеров" - 1 шт

**Comment by Georgiy163** [comment]
Ясно, будем верстать
