### ISSUE TITLE
Редактирование заказа. Кнопка "скопировать" копирует лейбл, а не инпут.

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#102]
И это делают все кнопки "скопировать" на этой странице.
![Screenshot_2](https://user-images.githubusercontent.com/88541095/231129273-1c0e5ffe-32e8-4db9-b657-f643fedec95b.jpg)

RM 1.0.6dev

**Comment by Septdir** [comment]
Fixed
