### ISSUE TITLE
Выбор категорий для фильтра товаров в админке

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#103]
Кажется логичным, если в фильтре по категориям будут только категории типа "Категория". Ведь для производителей и бейджей есть свои отдельные фильтры.

![Screenshot_2](https://user-images.githubusercontent.com/88541095/232142595-81ed7d35-adb6-4bf6-bae9-ee6cdd243171.jpg)

PS сейчас в отмеченном блоке и категории, и производители, и бейджи.

**Comment by Septdir** [comment]
Спорно, потому-что так было изначально и народ привык что все это категории

**Comment by Septdir** [comment]
Плюс там дерево выводиться так что оставим как есть
