### ISSUE TITLE
Алфавитная сортировка списка фильтров в админке

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#104]
Предложение для будущих релизов сделать сортировку вот этого списка (список фильтра по категориям/производителям/бейджам на странице товаров в админке) по алфавиту. Вещь не самая жизненно необходимая, но более удобная, чем сортировка по id в этом списке.

![photo_2023-04-27_09-03-02](https://user-images.githubusercontent.com/88541095/234853204-bc46d873-fa73-4969-a42d-bf39c7be5e6f.jpg)

**Comment by Septdir** [comment]
Там идет сортировка не по id а по "сортировке", так что можно настроить как удобно.
