### ISSUE TITLE
При падении в ошибку платежного плагина вывести кнопку оповещения администратора сайта

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#105]
Если плагин оплаты упал в 500 ошибку то нужно вывести сообщение "Оповестить администратора сайта о проблеме во время оплаты".
и кнопку отправить

**Comment by Septdir** [comment]
Добавлена позиция модуля.
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/3c56c96e-7384-4e81-999d-da433157d2ef)
