### ISSUE TITLE
[RM-UIkit] верстка на checkout при неразрывном названии товара

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#109]
<img width="1270" alt="Снимок экрана 2023-05-12 в 22 27 31" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/88d60148-dba8-48fc-90be-028bf9dadffc">

неразрывное название товара:
KSGY26HZRN1/KSRY26HZRN1 

верстка вот так ломается

**Comment by Septdir** [comment]
Дубль
