### ISSUE TITLE
Личные данные и настройки пользователя объединить в одну страницу

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#11]
Личные данные и настройки пользователя - я бы объединил в одну страницу. по аналогии оформления заказа на одной странице, так и редактирование инфы о юзере удобнее в одном месте

**Comment by Septdir** [comment]
Для разделения этих опций есть причина. И он кроется в автозаполнение полей.
Вот зашел ты опечатку в Имени или Адресс исправить, а после на сайт зайти не можешь. Плюс email для входа и контактный email - это могут быть два разных адреса.

P.S Система устроена так что если понадобиться для конкретного клиента это можно переопределить.
