### ISSUE TITLE
[RM-Module-Cart] мелкие правки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#111]
`<a radicalmart-cart="display_module" class="uk-link-reset radicalmart-icon" uk-tooltip="" aria-describedby="uk-tooltip-103" tabindex="0" title="">`

1. aria-describedby="uk-tooltip-103". это читалка экрана и озвучит. нужно осмысленное название написать, по-хорошему, с учетом локализации. Корзина  / Cart
2. google pagespeed не нравится иконка.  Links are not crawlable 

<img width="1015" alt="Снимок экрана 2023-05-14 в 13 20 16" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/78d00960-fbc0-4c83-8bba-a3f85400ff2f">
нужно  вместо тега A использовать тег button

3. смотрю исходный код магазина. 
**модуль фильтра** - 3 пустые строки. 
**модуль корзины**  - одна пустая строка.
ни на что не влияет, мелочь, но лучше пофиксить.

![2023-05-14 13 24 48](https://github.com/RadicalMart/Bug-Tracker/assets/3432048/01446acf-6744-4992-b896-334a745c6f30)

**Comment by Sulpher** [comment]
а еще лучше вместо aria-label сделать title - так подсветится пояснение и на десктопе и читалка тоже это принимает.

**Comment by Septdir** [comment]
Ну по вервому смысле не вижу. Второе поправил.
