### ISSUE TITLE
Плагин для WYSIWYG редактора для вставки товара

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#112]
Нажимаю кнопку и вижу: список товаров визуально некликабелен (не меняется курсор на палец при ховере), однако по клику вставляется товар, но окошко не закрывается. я думал, что баг. накликал, ничего не меняется, закрыл модалку, а в редакторе куча макросов.

нужно:
1. закрывать окно при выборе товара 
2. изменить логику и делать ссылки, чтобы визуально было видно, что элемент кликабелен

**Comment by Septdir** [comment]
В новом RME 2.0 c этим проблем нет.
