### ISSUE TITLE
[RM-UIkit] в списке товаров нет фильтра при просмотре в Ipad

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#114]
Вьюшка "все товары". слева в сайдбаре фильтр по параметрам, если переключиться на ipad, то фильтра нет.
предлагаю в шаблоне выводить сайдбар или сверху или снизу, но не отключать его

**Comment by Septdir** [comment]
На ipad выводиться позиция filter-mobile она в offcanvas
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/7429f594-1713-4260-b125-4689c32a4dbf)
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/d8320a36-3d8c-44bf-8b88-4135b19835cc)
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/1ade9009-5a7e-49a0-8485-312e9bb62a09)
