### ISSUE TITLE
Предупреждения в отладке оплаты

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#116]
![2023-05-18_23-49-47](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/3ab4526f-7b1b-4044-ae7f-44d5b965dec4)

**Comment by Septdir** [comment]
Это как ты умудрлся попасть на фатал без ордера?

**Comment by Septdir** [comment]
Пофикшено
