### ISSUE TITLE
Параметр "артикул" в способах доставки и оплаты

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#12]
вопрос: зачем нужен параметр "артикул" в способах доставки и оплаты?
<img width="482" alt="Снимок экрана 2021-10-19 в 14 27 21" src="https://user-images.githubusercontent.com/3432048/137900450-37c1dae3-3bb9-4824-956e-8ba871b31bc5.png">
комментарий 1: Там требуют часто передавать артикулы, в том числе. Особенно, если подключен офд к агрегатору

комментарий 2: так одно дело - передача артикула товара (автоматизация), другое дело - кастомное поле в настройках способа оплаты/доставки. вот это не пойму пока что...

**Comment by Septdir** [comment]
Ну справедливости ради поле артикул в "способах" нужно для того чтобы если попросят его туда не добавлять.
плюс доставка может быть товаром.
