### ISSUE TITLE
Админка: размер значения в alt параметре галереи

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#120]
<img width="1075" alt="Снимок экрана 2023-05-27 в 18 56 35" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/af9ee94e-e753-46b1-883f-887a6e71b120">

тут видно, что пустое значение alt - маленький шрифт. а если заполнить значение -  обычный. нужно привести к единому стандарту оформления, чтобы размер шрифта был один. 
если это отличается от Joomla стандарта

**Comment by Septdir** [comment]
Тут сделанно как в самой Joomla.
