### ISSUE TITLE
Не подсвечивается незаполненное поле при сохранении мета-товара

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#121]
начинаешь искать, что не заполнил. тратится время. нужно или красным выделять поле, либо писать название поля в сообщении об ошибке.

**Comment by Sulpher** [comment]
из чата:
_На скриншоте не заполнено и выделено поле название.
Там видимо у поля не стоит required в xml формы, а проверка в модели или в таблице сидит_

**Comment by Septdir** [comment]
Вопрос к Joomla. То что поле requed не светится если оно без фокуса

**Comment by Sulpher** [comment]
если целесообразно, напиши техническим языком проблему, я переведу на англ и закину в github joomla.

**Comment by Septdir** [comment]
Да там оно было уже. Но в там так и не договорись. 
P.S Я и сам написать могу.
