### ISSUE TITLE
Добавить кнопку быстрого доступа в медиа менеджер

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#122]
работаю с товарами. загружены картинки. и тут я решил их заменить (png на jpg). но нет кнопки быстрого вызова медиа.
пришлось минусами удалить все картинки и заново накидать.
но это неудобно, ведь могут быть alt или нужно одну картинку заменить. предложение: добавить. кнопку быстрого вызова модалки с media. 
если это потом решится через JyProExtra, то тогда будет отлично.

но это мелочь, улучшения.

**Comment by Septdir** [comment]
Это получиться сколько картинок, столько и медия менеджров. Плюс это можно сделать плагином сменив стандартный меди тип image на свой.
