### ISSUE TITLE
[RM-UIkit] вертикальная центровка стрелок в карточке товара

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#127]
Если сделать изображение квадратным и чуть увеличить мини-эскизы в размере, то стрелки влево-вправо улетают ниже середины. там переверстать нужно.  по тому что центровка стрелок идет не по большому изображению, а по всему контейнеру включая мини-эскизы, от этого вертикальное центрирование визуально работает неверно.

**Comment by Septdir** [comment]
Это центрование uikit слайдшоу.
