### ISSUE TITLE
Страница товара: отображение даты в скидке

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#128]
<img width="387" alt="Снимок экрана 2023-05-30 в 11 55 53" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/eba0a2a2-127a-4faa-9db2-38cedec1c420">

звучит неправильно, здесь два момента:
1. поменять `Text::_('DATE_FORMAT_LC1'));`
2. поменять локализацию и написать вместо до предлог по:
не до вторника, а по вторник
и после скидка я бы двоеточие поставил.

Скидка: 3 450.17 ₽ до вторника, 27 июня 2023 
Скидка: 3 450.17 ₽ по вторник, 27 июня 2023

**Comment by Septdir** [comment]
Заменино на DATE_FORMAT_LC6
