### ISSUE TITLE
[RM-UIkit] искажение пропорций аватарки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#129]
беру горизонтальную фотку, загружаю, ее пропорции становятся квадратными  и изображение выглядит искаженным, как пример ниже:
<img width="334" alt="Снимок экрана 2023-05-31 в 10 03 47" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/64446ed5-c718-40fd-86aa-d286a4ca2bd8">
нужно в текущей редакции убрать height.

а по-хорошему, должен быть кроппинг аватарки, тк могут загружать в несколько мб фотку. 
для кроппинга нужна внешняя либа. 
просится отдельный плагин.

**Comment by Sulpher** [comment]
кстати, а где в шаблоне можно убрать высоту?
в sidebar.php вижу это:
`<?php echo HTMLHelper::image(($avatar) ? $avatar : 'com_radicalmart/no-avatar.svg',`
а где лежит код, вызываемый image(($avatar))? это из недр компонента тянется?

**Comment by Septdir** [comment]
Это родной cover uikit
