### ISSUE TITLE
Сайдбар с элементами управления в админке - нужен отступ справа

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#13]
Справа от сайдбара нужен отступ, т.к. элементы вплотную к краю браузера выводятся
<img width="482" alt="Снимок экрана 2021-10-19 в 14 27 21" src="https://user-images.githubusercontent.com/3432048/137900607-ef552be9-fd54-433f-b459-93170f9da631.png">

когда будете портировать под j4, то можно не учитывать и сделать под новый интерфейс

**Comment by Septdir** [comment]
Уже скоро портировать, так что сейчас не вижу смысла с этим морочится.
