### ISSUE TITLE
[RM - UIkit]  разный цвет у label статуса заказа

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#130]
на фронте на странице заказа label у статуса товара не меняется:
<img width="824" alt="Снимок экрана 2023-05-31 в 11 14 54" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/197b3b9e-948a-4189-9e17-c43741b99a58">

отменен - логино сделать как danger.

**Comment by Septdir** [comment]
Это делаеться в админке в редактировании статуса
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/af7e3b83-ae15-42f3-95c9-47904b970212)

**Comment by Sulpher** [comment]
ух. супер. 
поставишь в новой версии разные классы значениям по умолчанию или и так сойдет?

**Comment by Septdir** [comment]
Не выйдет по умолчнаию. По умолчанию ставятся классы bs
