### ISSUE TITLE
[RM-UIkit] Checkout верстка

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#132]
default_sidebar.php
здесь кодировка UTF-8. я поменял на Western ISO Latin 1 по стандарту и вот тут символ валится: 
```

			â<span radicalmart-checkout-display="total.discount_string">
				<?php echo $this->item->total['discount_string']; ?>
			</span>
```

это тире в скидке

нужно заменить на HTML символ: `&minus;`

**Comment by Septdir** [comment]
```
здесь кодировка UTF-8. я поменял на Western ISO Latin 1
```
Если ты будешь менять кодировки то у тебя пол сайтов посыпеться ведь из базы приходит тоже utf-8
