### ISSUE TITLE
Email template - цвет скидки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#135]
<img width="781" alt="Снимок экрана 2023-06-19 в 20 11 55" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/4e02ea6d-ad61-4ea1-a949-bb34108001f2">

предлагаю цвет скидки с серого на красный сделать

**Comment by Septdir** [comment]
Переопределение в помощь.
