### ISSUE TITLE
Список товаров: принудительный переход на 1 страницу при смене сортировки

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#137]
Момент для обсуждения. Морда, список товаров. Дефолтная сортировка. Листаем до, положим,  страницы 5. Затем меняем сортировку на, например, "сначала недорогие". Страница обновляется, но мы до сих пор на 5 странице. Но кажется, что клиент ожидал бы оказаться на 1 странице, чтобы начать смотреть самые недорогие или самые новые с самого начала. По крайней мере я бы ожидал именно такого.

**Comment by Septdir** [comment]
Логично. Сделал.
