### ISSUE TITLE
[RM] Кнопка "на 1 место" в админке в списке товаров

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#138]
Хочется иметь в админке в списке кнопку "на первое место", которая перемещает выбранный товар на первое место при ручной сортировке. С учётом сложности реализации, возможно сделать её активной только в отсутствие прочих фильтров (как то по категориям категории и т.п.).

Иначе, если потребуется переместить товар с позиции 1500 на позицию 1, потребуется выставить отображение всех товаров списка, а следом тащить его мышкой на 1500 строк вверх, что на деле очень тяжело выполнимо.

**Comment by Septdir** [comment]
Подобное скорее всего надо делать в форме товара. Чтобы не выбирали 20 товаров и не делали их "Первыми"

**Comment by mius-it** [comment]
Был опыт работы с подобной схемой. Было удобно, когда в строке товара в списке была кнопка (иконка с тайтлом "на 1 место"), которая сразу же производила действие над этим товаром. То есть не выбрать товар галкой, а потом в панели действий выбрать действие, а сразу по кнопке. Но решение в форме товара тоже имеет место быть, чтобы не замусоривать список товаров. Главное, чтобы оно было :)

**Comment by Septdir** [comment]
Думаю тогда просто разделим. Пока сделаем в форме. А потом подумаешь как в списке сделать

**Comment by Septdir** [comment]
В форму добавил.
