### ISSUE TITLE
Плагины оплаты - нет иконки копирования в настройках поля

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#139]
<img width="737" alt="Снимок экрана 2023-06-25 в 20 04 42" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/215dce80-c229-417b-add5-adfb80fe741d">
по аналогии в остальных методах оплаты то же самое

**Comment by Sulpher** [comment]
на уровне архитектуры, патчить плагины не нужно?

**Comment by Septdir** [comment]
Не нужно. Это баг вылез из-за 4.3.3 обновления ядра.
