### ISSUE TITLE
параметр иконка в настройках категории

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#14]
вопрос. настройка категории. 
что значит параметр иконка? 
если uikit, то нужно поле для ввода класса. если это какой-то элемент поверх картинки категории, то я его не вижу

<img width="507" alt="Снимок экрана 2021-10-19 в 14 26 20" src="https://user-images.githubusercontent.com/3432048/137901035-957a62df-af2a-422f-8ede-28032392768c.png">

это какой-то элемент поверх картинки категории, то я его не вижу.
список категорий. картинка есть, иконки нет:
<img width="463" alt="Снимок экрана 2021-10-19 в 14 30 14" src="https://user-images.githubusercontent.com/3432048/137900953-9998190e-02ae-433d-8df7-d1ae976c2d76.png">

**Comment by Septdir** [comment]
Иконка используется в бейджах и производителях. В списке категорий в стандартном шаблоне используются обе. Приоритет изображение, если оно пустое то иконка.
