### ISSUE TITLE
Группа полей - нет иконки и действия для отключения/включения

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#141]
группа полей - нет иконки и действия для отключения/включения. так задумано или пропустили?
<img width="1250" alt="Снимок экрана 2023-07-01 в 15 52 06" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/4ff611f0-21f3-4d6d-a287-32f2bf549334">

**Comment by Septdir** [comment]
И не будет. Это feildsets либо удаляй. Либо оставляй.
