### ISSUE TITLE
[RM-Module-Filter] Uncaught TypeError: this.closest(...) is null

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#142]
нужно добавить ссылку "сбросить все"

я выбрал значения в фильтре, контент поменялся.
когда параметров много, то сразу и не найдешь, какой параметр выбран, чтобы его снять.

<img width="325" alt="Снимок экрана 2023-07-02 в 16 11 30" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/f041b256-cd70-4c5f-ba86-547378cb2321">

предлагаю добавить ниже кнопки "поиск" кнопку "очистить все". стандарт де факто для инет магазинов

**Comment by Sulpher** [comment]
кажется,  я понял. есть ссылка очистить, только она выводится не внизу, а после первого параметра и по клику не срабатывает. в консоли ошибка:
**Uncaught TypeError: this.closest(...) is null**

`onclick https://site.ru/katalog?filter[in_stock][all]=1&filter[fields][sostoyanie]=chasy:1`

**Comment by Sulpher** [comment]
и вот еще заметил: default шаблона на cassiopeia выводит у первых двух дефолтных параметров ссылку "очистить":
<img width="337" alt="Снимок экрана 2023-07-02 в 23 16 25" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/8424f124-7ce6-43e2-b9f7-53834580e2aa">

а вот так в uikit:
<img width="368" alt="Снимок экрана 2023-07-02 в 23 16 38" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/6bd1102c-834f-4201-88e8-4cfef5ef0470">
а здесь "очистить" не выводится ниже полей с ценами.

ну а у кастомных полей нет такой ссылки вообще.

**Comment by Septdir** [comment]
При клике на которую кнопку выскакивает `Uncaught TypeError: this.closest(...) is null`

**Comment by Septdir** [comment]
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/3d6d6d2a-4d5c-42c4-9a4f-50f7f4cab6e8)

**Comment by Septdir** [comment]
Сделано
