### ISSUE TITLE
Скрытие названия категории в списке товаров не работает

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#143]
Отключаю в настройках категории параметр отображения категории в списке товаров:

<img width="1366" alt="Снимок экрана 2023-07-02 в 22 32 55" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/6a60092e-6da0-4d2a-9046-f73cfad846c2">

но на фронте без изменений - название выводится. в карточке отключается. видимо, ошибка в условии.

проверил на дефолтном и Uikit шаблонах

**Comment by Septdir** [comment]
В списке товаров, как и некоторый других местах, выводиться главная категория -`$item>category`, а на нее этот параметр не влияет.
На бейджи и производителей. Если хотите чтобы у вас списке выводились все категории и этот параметр влиял. Вместо `$item>category` и используйте `$item>categories` циклом
