### ISSUE TITLE
[RM] Не выставляются данные зарегистрированного пользователя при оформлении заказа

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#144]
Сценарий: неавторизованный пользователь собирает корзину, переходит к оформлению и видит незаполненные поля фио, адреса и т.п. Пользователь ранее регистрировался и понимает, что не авторизован. Успешно авторизуется, возвращается в корзину и переходит к оформлению заказа и вновь видит пустые поля.

Полагаю, что данные для автоматической подстановки берутся из куков, игнорируя данные из профиля пользователя.

**Comment by Septdir** [comment]
Есть ли у этого пользователя данные покупателя?

**Comment by mius-it** [comment]
> Есть ли у этого пользователя данные покупателя?

Да. Есть и данные покупателя, и данные доставки.

**Comment by Septdir** [comment]
Сделано

**Comment by Septdir** [comment]
Принцип такой при логине чекается заполнено ли хоть одно поле в контактах в оформлении. Если не заполнено то срабатывает подстановка из профиля

**Comment by mius-it** [comment]
Снова столкнулся с подобным поведением. RM 1.2.0. Сценарий тот же. Теперь контактные данные выставляются верно, а вот данные доставки (стандартная доставка) из его профиля не подтягиваются - остаются пустыми.
