### ISSUE TITLE
Пустые данные для стандартной доставки

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#146]
Клиент оформляет заказ, используя модуль "Стандартная доставка". В админке заходим в редактирование заказа. И тут натыкаемся на ошибки:

1. Переходим на вкладку доставки и видим, что доставка не выбрана. Изменяем вручную на "стандартная доставка" и видим пустые данные для доставки. Ошибка случилась 2 раза, после не смог повторить.

2. Другой случай: в админке во вкладке доставки видим выбранную стандартную доставку, видим заполненные поля, всё хорошо. Выбираем любой другой способ доставки или же нулевую строку "выберите способ доставки". Затем снова выбираем "стандартную доставку" - и вот у нас снова пустые поля, форму сохранить невозможно.

**Comment by Septdir** [comment]
1. Не могу починить то что нельзя повторить. Это могло случиться по разным причинам. К примеру у вас в сессии у этого заказа висит не выбранная доставка или еще что-нибудь. вплодь до кривого переопределения шаблона.

2. Это нормальное поведение. При смене способа доставки, поля должны очищаться.  Нажимаете отмена и открываете заного.
Просто пример. Два плагина доставки у одного поля адрес должно включать страну, у другого по формату нет.
