### ISSUE TITLE
Дополнить статусы заказов

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#15]
Добавьте такое:

- Возврат 
- Частичный возврат (имеется ввиду, когда покупателю возвращают часть суммы от товара, т.н. partly refund)

**Comment by Sulpher** [comment]
вижу статус "подтвержден"
мне кажется, нужно добавить еще такой: в обработке (pending)
либо это то же, что и подтвержден.  назначать по умолчанию заказу.

**Comment by Septdir** [comment]
Статусы можно и нужно делать свои. Базовые статусы нужны чтобы магазин работал сразу после установки.
Возврат можно будет добавить после создания функционала возврата, который в планах.
