### ISSUE TITLE
Добавление целей я.метрики к стандартным действиям

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#151]
Есть предложение в настройках RM добавить возможность прописать код целей яндекс-метрики для стандартных действий, таких как "положить в корзину", "перейти к оформлению", "оплатить". Пользователю это определённо было бы полезно, хоть всё это можно и в коде шаблона прописать.

**Comment by Septdir** [comment]
Все уже есть.
```
	document.addEventListener('RadicalMartTrigger', function (event) {
		if (event.detail) {
			if (event.detail.action) {
				console.debug(event.detail);
				if (event.detail.action === 'add_to_cart') {
					console.log('Добавлено в коризу')
				}
			}
		}
	});
```

Сами action и данные можно смотреть включив отладку joomla и консоле будет видно.
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/9179db07-73f0-4d47-97f1-44c4b2789425)

**Comment by mius-it** [comment]
Я имел в виду сделать это заполняемым полем в админке джумлы в настройках RM. Пользователям без технических умений это было бы удобно. Плюс "интеграция с яндекс-метрикой" - это неплохая маркетинговая фишка, как мне кажется.
