### ISSUE TITLE
[JL Sitemap] Исключить страницы из индексации

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#152]
Добавить noindex, nofollow для следующих страниц:

- Корзина
- Оформление заказа
- Настройки
- Заказы

последние два пункта под вопросом. лучше единый стандарт применить.  
первые два попадают в JL Sitemap.

**Comment by Septdir** [comment]
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/ddff9e52-0e08-421c-8e8a-74fc0586afe1)
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/6f316ff9-b733-4dc6-bade-c13850c23840)
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/1502ea0e-8e41-4cac-a2f7-bd4a2ac3718c)

В ядре у этих страниц noindex, follow  у этих страниц. Оставляю открытым из-за JL

**Comment by Sulpher** [comment]
а зачем роботу туда заходить?

**Comment by fiction13** [comment]
Первые 2 пункта надо исключить в настройках JL Sitemap.

**Comment by Sulpher** [comment]
как  по мне, так либо noindex, nofollow, либо вкладку robots в пунктах меню добавить. пусть вебмастер решает.
хотя зачем это нужно - непонятно. все равно нужно закрывать от индексации

**Comment by fiction13** [comment]
@Septdir закрывай, с моей стороны тут править нечего.
