### ISSUE TITLE
Нет картинки у удаленного товара на странице заказа

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#154]
<img width="986" alt="Снимок экрана 2023-07-15 в 13 21 42" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/c0d7bbc7-e2b8-427d-8518-c05b2e7fd24d">

старый заказ с товарам. я не помню уже, либо часть товаров  была удалена, либо изменена.  по факту, такого товара сейчас нет.
в макете мы видим: нет картинки и ссылка # 

нужно сделать проверку и не выводить ссылку (якорь # излишен) и для картинки выводить заглушку noimage

**Comment by Septdir** [comment]
Добавлена проверка

**Comment by Sulpher** [comment]
шаблон uikit нужно патчить?
