### ISSUE TITLE
Модульные позиции

### ISSUE THREAD

**Issue by Septdir** [RadicalMart/Bug-Tracker#155]
Какие позиции добавить и где их выводить
etc. `radicalmart-category-after-introtext` - Выводить под кратким описание категории

**Comment by Taatshi** [comment]
Хотелки пишу по максимуму, дальше сам умеришь мои аппетиты)
1) Корзина до и после содержимого
2) Оформление заказа
 - две позиция общих для всех станиц - над и под инфой
 - на каждой странице оформления заказа по две позиции именно для текущей страницы - сверху и снизу инфы
 3) Карточка товара
 -  до и после описания две позиции
  - еще одну под заголовком, но это не точно)
4) В списке товаров 
 - одну плавающую как под товар чтобы рандомно возникала с указанием на какое кол-во товаров, например, один раз на 100 товаров или на страницу
 - одну под заголовком
 - одну после описания категории или страницы

**Comment by Septdir** [comment]
Добавлены
