### ISSUE TITLE
[RM] Изменение статуса публикации категории влияет на публикацию товаров

### ISSUE THREAD

**Issue by MSGroupFM** [RadicalMart/Bug-Tracker#156]
Ошибка заключается в том, что при изменение состояния категории влияет на все дочерние товары, независимо от их текущего статуса. То есть если распубликовать категорию, в которой есть товары со статусом "В корзине", то эти товары перейдут в статус "Не опубликовано".
А если опубликовать категорию, то все товары, даже находящиеся в корзине, будут опубликованы на сайте.
Версия в которой воспроизводится ошибка: RadicalMart 1.1.1
Класс Joomla\Component\RadicalMart\Administrator\Model\CategoryModel 
Метод publish
Фрагмент кода

```
$set = (int) $value;
if ($value === -2)
{
	$set = 0;
}
$query = $db->getQuery(true)
->update($db->quoteName('#__radicalmart_products'))
->set('state = ' . $set)
->where($db->quoteName('category') . ' IN (' . implode(',', $pks) . ')');
```

**Comment by Septdir** [comment]
Так ну я убрал.
