### ISSUE TITLE
[RM] Ошибка при обработке символа & в фильтре категорий

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#158]
вот производители. если в названии встречается амперсанд, то выводится число:
<img width="1210" alt="Снимок экрана 2023-07-24 в 15 23 56" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/367ea3f6-a207-4d7b-aad5-197e6e01ed87">

**Comment by Septdir** [comment]
Пофикшено
