### ISSUE TITLE
Скидка продолжает действать после дня окончания

### ISSUE THREAD

**Issue by andreytver84** [RadicalMart/Bug-Tracker#160]
Скидка не снимается после установленной даты окончания
https://lubimovka-market.ru/

**Comment by Septdir** [comment]
Пофикшено  Jun 1

**Comment by andreytver84** [comment]
> Пофикшено Jun 1

в админке RadicalMart версия 1.1.1 
нужно переустановить?

**Comment by Septdir** [comment]
У вас на сайте указаном в заголовке все работает.

--
Best regards, Igor Berdichevskiy

вс, 30 июл. 2023 г., 17:02 andreytver84 ***@***.***>:

**Comment by Septdir** [comment]
https://github.com/RadicalMart/Bug-Tracker/assets/18382023/95312afe-1171-4f9e-9986-6978f6f169ec


https://github.com/RadicalMart/Bug-Tracker/assets/18382023/ac5acc5c-7044-40ff-ae8b-82705c0f4497

**Comment by andreytver84** [comment]
В метатоваре нижний порог цены остаётся как будто скидка ещё действует. При погружении в карточку товара цена меняется на актуальную. Таким образом. Если мы ставим скидку на товар, то после окончания скидки нужно заходить и править диапазон цен в метатоваре

**Comment by Septdir** [comment]
Расчет минимальной и максимальной цены не имеет ни какого отношения к заголовку репорта.

**Comment by andreytver84** [comment]
Вот мне от клиента пришло.

"когда скидку устанавливаешь, диапазон в метатоваре сам меняется автоматически, а когда скидка проходит, то нет. Скидка в категории в списке товаров ПРОДОЛЖАЕТ ДЕЙСТВОВАТЬ"

Нужно новую ветку создать для решения?

**Comment by Septdir** [comment]
Конечно нужно.
