### ISSUE TITLE
[RM] Элемент интерфейса - вывести вкладку SEO во всю ширину

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#162]
<img width="1337" alt="Снимок экрана 2023-07-31 в 16 21 53" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/0dd3183d-c0cf-4c0a-b06e-d4cb24ab44e5">
собственно, здесь можно в одну ширину

**Comment by Septdir** [comment]
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/72c48dfc-ddf0-45ca-b78c-1406d51a4563)
Пофикшено
