### ISSUE TITLE
[RM] Опечатка в en-GB файле панели управления

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#166]
Буду писать опечатки,которые замечу.

<img width="417" alt="Снимок экрана 2023-08-01 в 17 35 10" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/50f65fb1-b3fd-4f25-8bed-de0a643f5255">

After titel
правильно: title

**Comment by Sulpher** [comment]
Мелочь. статус заказа cancelled.

у тебя canceled. должно быть двойное L: cancelled.
![Снимок экрана 2023-08-29 в 14 21 05](https://github.com/RadicalMart/Bug-Tracker/assets/3432048/993a7cb4-b38b-4432-ac74-ce31dce80659)

по логике и класс внутри настроек поправить нужно тоже:
<img width="713" alt="Снимок экрана 2023-08-29 в 14 24 34" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/05fb45f1-2e7b-41e0-8cc5-9709191d6227">

**Comment by Septdir** [comment]
Первое поправил.
Насчет второго я все же оставлю US вариант с 1L. Потому что от правки могут возникнуть проблемы
