### ISSUE TITLE
[RM] диапазон цен в метатоваре не меняется обратно после завершения действия скидки

### ISSUE THREAD

**Issue by andreytver84** [RadicalMart/Bug-Tracker#167]
когда скидку устанавливаешь, диапазон в метатоваре сам меняется автоматически, а когда скидка проходит, то нет. Скидка в категории в списке товаров ПРОДОЛЖАЕТ ДЕЙСТВОВАТЬ

**Comment by Septdir** [comment]
Добавлена команда которую можно запускать по cron
`radicalmart:calculate:metas:prices`
