### ISSUE TITLE
Список стран, импорт регионов и НДС

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#17]
Для дальнейшего масштабирования магазина, нужно предусмотреть загрузку списка стран. а при загрузке определенной страны, чтобы подтягивался список регионов, городов.
страны и регионы нужно иметь возможность отключать.

и такая возможность должна быть в любой момент.
предлагаю выбор из 3х ступеней:
- импорт списка стран
- импорт списка регионов страны
- импорт городов выбранных регионов

архитектурно заложить рядом поле с НДС.  это пригодится на будущее для США и ЕС, когда в зависимости от странф или штата меняется НДС на заказ.

можете посмотреть в Phoca Cart или Virtuemart (там, кажется, тоже было), как сделан импорт данных стран/регионов.
возможно, интеграция с внешней библиотекой, которая будет вытягивать данные и обновлять их.

**Comment by Septdir** [comment]
Будет тут #41
