### ISSUE TITLE
[RM] При небольшой ширине экрана не помещаются кнопки выбора столбоцов

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#171]
Если у компьютера небольшая ширина экрана, то кнопки выбора столбцов не помещаются в экран

<img width="1478" alt="Снимок экрана 2023-08-18 в 12 16 10" src="https://github.com/RadicalMart/Bug-Tracker/assets/3103677/cd58c6eb-7d5a-40a4-a8db-c55cea377754">

для столбца "Состояние" предлагается сменить название и поменять его на иконку list-check

<img width="573" alt="изображение" src="https://github.com/RadicalMart/Bug-Tracker/assets/3103677/371cf06a-2af9-42e6-bb98-e4039a679b9e">

Для "Дополнительной категории" сменить на "Доп. категории"

**Comment by Sulpher** [comment]
заметка:
> "Для "Дополнительной категории" сменить на "Доп. категории"" 

сразу на будущее: если когда-то  придет время переводить на другие языки, то возникнет та же проблема.
Zusätzliche Kategorie или Additional categories. 
Мы не можем сократить в англ. до Add.categories, т.к. возникает ассоциация со словом add (добавить).
тут нужен костыль в css в виде nowrap, либо ждать, когда в Joomla админку улучшат. 
а пока сократить в русской версии.

**Comment by progreccor** [comment]
для английского можно использовать Extra

**Comment by Septdir** [comment]
Вроде переделали уже.
