### ISSUE TITLE
[RM] Скрывать пароль в сообщении о регистрации (настройка из com_users)

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#176]
не спроста в Joomla добавили опцию и по умолчанию ее выключили:
<img width="849" alt="Снимок экрана 2023-08-21 в 16 41 35" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/161fac1e-ef32-4b85-a768-d5943cc42921">

а вот какое письмо приходит при первой покупке в RM:

_Евгений, для вас на сайте site.ru автоматически создана учетная запись.
Вы можете в любой момент времени авторизоваться на сайте site.ru используя
Логин 55555555555
Пароль ******* (я закрыл)_

нужно делать проверку и брать значение из настроек com_users. если там скрыть пароль, то и в письме RM не надо присылать

**Comment by Septdir** [comment]
У нас поля ввода пароля. Он генерируется автоматически и рандомно. 
И если мы учтем эту настройку, человек если сразу же не сменить пароль (а он может не авторизоваться или еще по какой причине) больше он на сайт не войдет.

В Joomla же пароль вводится руками и суть этой настройки в том, чтобы скрыть данные введённые пользователем. А не его пароль.
