### ISSUE TITLE
[RM-Messages-Email] Опечатка в письме при регистрации

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#177]
Вы можете в любой момент времени авторизоваться на сайте site.ru используя

после адреса сайта нужна запятая.
пример:

Вы можете в любой момент времени авторизоваться на сайте site.ru**,** используя

**Comment by Septdir** [comment]
Опасно ставить запятую рядом с адресом сайта, оно может попасть в href
