### ISSUE TITLE
[RM] при создании товара если не выбрать поле - непонятно чего не хватает

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#178]
нужно подсветить визуально незаполненное поле или написать какое
<img width="1862" alt="изображение" src="https://github.com/RadicalMart/Bug-Tracker/assets/3103677/2210de7c-b9fb-4b98-a738-4fb722ab05b3">

**Comment by Septdir** [comment]
Объединяю в #244
