### ISSUE TITLE
Страница "спасибо за покупку"

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#18]
<img width="1228" alt="Снимок экрана 2021-10-19 в 14 55 53" src="https://user-images.githubusercontent.com/3432048/137905210-287a4dfc-285c-4b73-8fcd-5fb5ef1d6c89.png">

мне все время кажется, что еще не все действия завершены. нужно сообщение  "спасибо за ваш заказ. в ближайшее время мы с вами свяжемся" на чистом экране. и возможность этот текст кастомизировать. 
также можно вывести ниже текста кнопки "мои заказы", "к каталогу"

**Comment by Septdir** [comment]
Сделано

**Comment by Sulpher** [comment]
Это страница без шаблона с благодарностью, которая пропадает через 8 секунд и редиректит обратно?

**Comment by Septdir** [comment]
Нет - эта страница с шаблоном. И пунктом меню. 
![изображение](https://user-images.githubusercontent.com/18382023/145814089-c3cbd9e6-94e3-4e87-b479-6d112e77e872.png)

**Comment by Septdir** [comment]
![изображение](https://user-images.githubusercontent.com/18382023/145814206-8af29f9c-d1f6-4f68-8dac-10e451bea573.png)

**Comment by Sulpher** [comment]
видимо, будет в след.версии.
когда ты написал, что сделано. я подумал, что уже в текущей версии есть. 
можно в тикетах при ответе версию проставлять.

кстати, по картинке я не очень понял смысл:
перейти к заказу / перейти к оплате

получается, это до оплаты выводится? 
нужно же после оплаты вывести страницу с благодарностью. 
а если так делать, то нелогично отправлять юзера на страницу оплаты, ведь товар уже оплачен.

**Comment by Septdir** [comment]
> видимо, будет в след.версии.
В 1.0 или в какм либо dev

> получается, это до оплаты выводится?
да это станица благородности за заказ.
Стандартная страница done. Которая не зависит от способов оплаты и т.д
Можно кастомизировать, К примеру 
добавить менеджер с вами свяжется.
- купите так-же основываясь на составе заказа и т.д

> нужно же после оплаты вывести страницу с благодарностью.
Станица после оплаты вот https://github.com/RadicalMart/Bug-Tracker/issues/43

**Comment by Sulpher** [comment]
> Стандартная страница done. Которая не зависит от способов оплаты и т.д
так нет смысла благодарить до тех пор, пока не финализирован платеж.
а страница без шаблона выглядит странно. 
магазины после успешной оплаты возвращают обратно с шлюза и выводят сообщение с благодарностью.

текущая прослойка #43 в виде отдельной страницы выглядит избыточной. лучше такое выводить вьюшкой внутри сайта. имхо.

**Comment by Septdir** [comment]
> так нет смысла благодарить до тех пор, пока не финализирован платеж.
Стандартный сценарий. Благодарим вас за покупку наш менеджер свяжется с вами. А оплата идет только после подтверждения.

> а страница без шаблона выглядит странно.
Страница с шаблоном. Просто это отдельный tmpl, такой же, как и tmpl=component.  Сделано так для универсальности. Ибо часто на таких страницах надо убирать шапки и подвалы + выводить свои позиции модулей.
