### ISSUE TITLE
[RM] Кнопку "сохранить как мета товар" назвать "открыть как метатовар"

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#181]
Кнопка не сохраняет метатовар и по сути именно открывает текущий товар как метатовар и дает возможность его сохранить

**Comment by progreccor** [comment]
после открытия товара как мета-товара добавить сообщение "Мета-товар открыт для редактирования и сохранения. В данный момент он еще не создан и не сохранен."

**Comment by Septdir** [comment]
Done
