### ISSUE TITLE
[RM] в админке в таблице вывода товаров цену товара выравнивать вправо

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#182]
<img width="1953" alt="изображение" src="https://github.com/RadicalMart/Bug-Tracker/assets/3103677/13369188-b737-4b2c-abd3-1ef19a22c64a">
Цену надо выравнивать вправо
(в идеале вообще по десятичной точке)

**Comment by Septdir** [comment]
Done
