### ISSUE TITLE
[RM] Фатал при рендере поля filter_price

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#183]
![2023-08-21_22-51-56](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/55143395-9112-41da-b109-4421caa807c9)
![2023-08-21_22-48-19](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/66cd2f23-c1ff-49c5-8997-2fba3ebeec0a)
![2023-08-21_22-50-58](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/8989a0db-cd98-47f2-93c8-e065727beac9)

**Comment by Septdir** [comment]
Fixed
