### ISSUE TITLE
[RM] Контактные данные в оформлении заказа перенести в модалку

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#184]
Для примера взглянем на Озон:
<img width="1321" alt="Снимок экрана 2023-08-22 в 14 44 15" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/373f0a1f-34c6-4d90-8c80-4d437191825b">

здесь все просто и лаконично - мы сразу выбираем способ оплаты, не нужно скроллировать вниз.

смотрим RM:
выводится каждый раз авторизованному пользователю форма для заполнения контактных данных. 
это напрягает и, к тому же, человек пропускает выбор способа оплаты и доставки (там подставлены значения по умолчанию). 

давайте уберем эту форму в модальное окно и выведем кнопку: 
Получатетель: Имя Фамилия, телефон 
по нажатию можно будет заменить данные. 

так мы выиграем место и в плане юзабилити будет удобно старому пользователю не чекать каждый раз данные.

**Comment by Septdir** [comment]
В ядре нет. Я часто меняю получателя заказа. И модалки раздражают.

**Comment by Sulpher** [comment]
а если также заводить разные адреса получателей как в Озон и давать юзеру выбирать из набора?
как мысль на будущее

**Comment by Septdir** [comment]
А причем тут адрес и получатель. Получатель это тот кто будет получать заказ он же контактное лицо. Его меняют куда чаще чем адрес или способ доставки. Кому по пути тот заказ забирать и будет.
