### ISSUE TITLE
[RM] если не указать категорию при сохранении товара - не подсвечивает категорию

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#185]
при попытке сохранить товар без категории пишет что не все поля заполнены, но категория не подсвечивается

**Comment by Sulpher** [comment]
насколько помню, мы это обсуждали как-то чате. кажется, проблема в том, что сейчас используется стандартная логика Joomla.

**Comment by Septdir** [comment]
Объединяю в #244
