### ISSUE TITLE
[RM] Исправить дефолтное ограничения на subforms

### ISSUE THREAD

**Issue by CB9TOIIIA** [RadicalMart/Bug-Tracker#186]
Необходимо исправить дефолтное ограничения на subforms

Например в плагине: `/plugins/radicalmart_fields/standard/forms/products`

Протестировано - работает на list.xml

```		<field name="options" type="subform"
			   label="PLG_RADICALMART_FIELDS_STANDARD_OPTIONS"
			   multiple="true"
			   layout="joomla.form.field.subform.repeatable-table"
			   min="1"
			   max="1000000"
			   required="true">
```

![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/52f062c4-1a0b-44f4-8463-8f8e4f32b2a7)

P.S. Спасибо Диме (@fiction13)

**Comment by Septdir** [comment]
done
