### ISSUE TITLE
[RM] Payselection удаляется некорректно

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#187]
Иду в установщик Sovmart.  нахожу payselection и удаляю. 

поиском joomla не находит:
<img width="962" alt="Снимок экрана 2023-09-06 в 17 16 13" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/a2e5bd77-b792-4750-b6e0-e1b7f962d66d">

однако в списке методов оплаты он остался:
<img width="732" alt="Снимок экрана 2023-09-06 в 17 15 44" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/399babcc-1a32-4a8a-9903-486bfdde14c0">

<img width="1341" alt="Снимок экрана 2023-09-06 в 17 17 23" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/20fe73e9-9171-493a-971d-6fc2a0b64a39">

некорректное удаление через совмарт установщик. переустанавливаю через него же - настройки у плагина появляются.

удаляю через установщик joomla  -плагина нет, но в списке методов оплаты он остается и все то же самое.
словно дефолтный метод.

**Comment by Sulpher** [comment]
видимо, ошибка в xml манифесте

**Comment by Septdir** [comment]
Плагин и метод это метод оплаты это разные вещи.

Вот тебе стандартный пример что произойдет если при удалении плагина удалять метод оплаты.
Владелец создает способ оплаты "Онлайн" пишет описание, картинку ставит. Проходит время и он хочет сменить эквайринг.
Для этого он СНАЧАЛА удаляет ненужны плагин, ПОТОМ ставит новый.

Итог. В старых заказах пропал способ оплаты, в 1с сбой, в CRM сбой, в решении который ему написали для сайта и прицепились к id метода оплаты сбой.
Да еще и способ оплаты создавать заново создавать, при это описание было еще и красиво на html оформлено, а где лежала картинка он не помнит.
