### ISSUE TITLE
[RM] Добавить к валюте [без языка]

### ISSUE THREAD

**Issue by CB9TOIIIA** [RadicalMart/Bug-Tracker#188]
Сейчас, чтобы иметь 2 валюты, необходимо второй задавать (выбор языка), чтобы например USD->RUB.
Предлагается сделать пункт (без языка)

![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/90ea1eff-a0de-40e9-ac5d-04ac04fd4b59)

**Comment by Septdir** [comment]
Done
