### ISSUE TITLE
[RM] Снять выбор доставки и оплаты по умолчанию

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#189]
Вот что мы имеем на странице оформления:
<img width="1350" alt="Снимок экрана 2023-09-13 в 23 55 59" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/3a5e7c34-4471-44d3-9050-43458bdb1c7c">

чисто психологически неверно сразу выбирать по умолчанию первый способ. нужно снять выделение, чтобы юзер при попытке перейти дальше получил предупреждение и  выделить красным поля. это подтолкнет самостоятельно сделать выбор, изучив варианты. 

вот пример, здесь другой подход, но юзер должен выбрать опцию сам, она по умолчанию не выбрана:
<img width="1086" alt="Снимок экрана 2023-09-14 в 09 42 48" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/bbb4411a-232c-48bb-af88-8fe33a0ecb0a">

в противном случае юзер особо не заморачивается и перейдет дальше, не сделав правильный выбор.

**Comment by fiction13** [comment]
Не согласен, это нормальная практика.

**Comment by Septdir** [comment]
Это стандарт в переопределениях можно сделать мультишаговую форму.
