### ISSUE TITLE
Стандартный способ оплаты. Поле ссылка на оплату

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#19]
<img width="495" alt="Снимок экрана 2021-10-19 в 15 03 08" src="https://user-images.githubusercontent.com/3432048/137905483-26167840-4eaf-400a-9937-689e67546944.png">

способ оплаты. выбрал стандартный плагин, добавил в поле "ссылка на оплату" домен для проверки, но редиректа не произошло. не доделано еще?

**Comment by Septdir** [comment]
Это поле уже удалено.
