### ISSUE TITLE
[RM] Критическая ошибка при пустом меню, вынесенном в сайдбар

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#190]
![2023-09-19_10-40-32](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/952d4134-1f94-447e-abc8-eb8a87a3c880)
![2023-09-19_10-41-08](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/66238d72-e80b-477d-a0ec-4a4596075a4e)

**Comment by Septdir** [comment]
Done
