### ISSUE TITLE
[RM-UIkit] добавить li в макет пагинации

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#191]
проблема с иконкой последней стр:
<img width="979" alt="Снимок экрана 2023-09-19 в 12 13 02" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/0e54b7ce-7746-4878-a093-a52f7818946f">

дело в том, что нужно в коде в li обернуть:
```
		<?php if ($pages['next']['active']): ?>
			<a href="<?php echo $pages['next']['data']->link; ?>"
			   title="<?php echo Text::_('COM_RADICALMART_PAGINATION_NEXT'); ?>" uk-tooltip>
				<span uk-icon="icon:chevron-right; ratio:1.2"></span>
			</a>
		<?php else: ?>
**<li>**
			<span uk-icon="icon:chevron-right; ratio:1.2" class="uk-text-muted"
				  title="<?php echo Text::_('COM_RADICALMART_PAGINATION_NEXT'); ?>" uk-tooltip></span>
**</li>**
		<?php endif; ?>
```

и получаем правильный вариант:
<img width="930" alt="Снимок экрана 2023-09-19 в 12 13 21" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/f050965a-a9df-47b2-b807-eda5faded390">

**Comment by Septdir** [comment]
По дефолту они вне ul
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/e2fcb9f2-d0f5-4156-9fcf-b80212ff1985)
