### ISSUE TITLE
[RM] Опечатки в локализации #2

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#193]
курс валют:
ru-RU. **В ручную**. пишется слитно.

en-GB:
<img width="604" alt="Снимок экрана 2023-09-29 в 08 49 59" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/fe65e0cb-7673-4ff3-9d76-1858cecf208c">
лучше так:
No products.

**Comment by Sulpher** [comment]
en-gb:

<img width="660" alt="Снимок экрана 2023-11-06 в 22 09 08" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/cd327d3c-f92c-46c7-886d-42d59c6e97bd">

List лучше переименовать в Select. так понятнее

**Comment by Sulpher** [comment]
<img width="979" alt="Снимок экрана 2023-11-06 в 22 11 44" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/c65fa0ea-2079-4410-97c1-73645061d735">

**Comment by Septdir** [comment]
1. Сдеанно.
2. Нет тут list идет от Jform так что это корректнее.
3. Поправил но релиз полей не скоро.

P.S не объединяй разные расширения в одном Issue закрывать не удобно
