### ISSUE TITLE
[RM] Добавить опцию при сохранении товара "Сохранить и создать"

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#194]
<img width="744" alt="Снимок экрана 2023-09-30 в 11 52 24" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/901594d2-d69b-4d97-9460-6267072abd23">

Вот как в com_content. очень удобно, когда забиваешь сайт  рыбой - структурой, когда нужно накидать статей или просто работать массово. 
аналогично предлагаю сделать и в РМ:
<img width="652" alt="Снимок экрана 2023-09-30 в 11 51 30" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/6e4debbb-4699-4229-9cf8-85de52c76a2e">

вот набиваю магазин товарами-рыбой чтобы было с чем работать и массовые действия - нужно выиграть секунды за клик. удобнее сразу не выходя из режиме редактирования работать дальше.

давайте добавим такую опцию.

**Comment by Septdir** [comment]
Так вон она на скрине первая

**Comment by Sulpher** [comment]
ого. блин. вот это я заработался. да, действительно.
