### ISSUE TITLE
Не выводить таб,  если он один

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#2]
![3](https://user-images.githubusercontent.com/3432048/137892057-fafd1b9b-1093-4a7b-98fc-f7cf5a78e10c.jpg)

обратите внимание на кнопку обзор. не мог понять, что это. скорее всего, это таб? нужно сделать проверку и не выводить его, если нет больше 1 таба

**Comment by Septdir** [comment]
Вопрос верстки.

**Comment by Sulpher** [comment]
почему бы сразу не сделать правильно? чтобы не подправлять каждый раз
