### ISSUE TITLE
Группа параметров налоги/НДС

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#20]
добавить группу параметров "НДС/налоги" вот сюда:
<img width="323" alt="Снимок экрана 2021-10-19 в 15 04 54" src="https://user-images.githubusercontent.com/3432048/137905784-bf8d7261-7115-4b73-bb39-a5625bb7db29.png">

юзер сможет создавать значения с разными налогами.  в карточке товара можно выбирать. 

перекликается с налогами на страну/регион, описанную здесь:
https://github.com/RadicalMart/Bug-Tracker/issues/17

смысл в том, что в ЕС НДС отличается от страны к стране.
или какие-то товары имеют разный НДС. 

пример настроек из др.магазина
<img width="521" alt="Снимок экрана 2021-10-19 в 15 07 10" src="https://user-images.githubusercontent.com/3432048/137906121-e0b2fc09-e9e3-4101-8b36-ca17899ee349.png">

**Comment by b2z** [comment]
Кроме того, чтобы поддерживать НДС, например в Сбере для товара, если передавать tax, надо не только taxType (ставка НДС), но и taxSum (сумма налога, высчитанная продавцом). И проблема с taxSum - его нету в товаре. То есть tax по сути передать невозможно :cry:

**Comment by Septdir** [comment]
> 

Ну ты можешь его рассчитать сам.
А вообще, навреное надо в паремметразх товаров, в глобал настройках и может еще в категории.

**Comment by b2z** [comment]
@Septdir ну нет, это обязанность магазина. Платёжный плагин не должен таким заниматься.

**Comment by b2z** [comment]
@Septdir  с taxSum обманул - этот параметр необязательный ;)

**Comment by Septdir** [comment]
#41 Будет тут
