### ISSUE TITLE
[RM] Прогнать компонент через JED Checker на предмет исправлений

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#200]
Вот что выдает [JED Checker](https://extensions.joomla.org/extension/jedchecker/): 
<img width="1073" alt="Снимок экрана 2023-10-30 в 08 18 44" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/70ec572c-6e0a-476c-85a9-4597002b17ca">

разумеется, это не для выкладывания на JED, но это - полезная утилитка для  приведения к стандартам там, где нужно.

например:
PHP Files missing JEXEC security 

остальное по обстоятельствам.

**Comment by Sulpher** [comment]
**PHP Files missing JEXEC security**
All the PHP files in your extension needs to have a defined('_JEXEC') or die(); statement in the beginning of each file. This ensures that the file cannot be opened outside of the joomla installation and increases the security of your site. 

`#001 /com_radicalmart/admin/src/Helper/AssociationsHelper.php`
The JEXEC security check was not found in this file.
`#002 /com_radicalmart/admin/src/Table/PaymentMethodTable.php`
The JEXEC security check was not found in this file.
`#003 /com_radicalmart/site/src/Traits/ItemCategoriesModelTrait.php`
The JEXEC security check was not found in this file.



**XML Manifests**
Validation of extension's XML manifest file
#001 /com_radicalmart/radicalmart.xml
Node <extension> contains unknown <layouts> element



**JAMSS - Joomla! Anti-Malware Scan Script** 
JAMSS will raise many flags for use of potentially dangerous methods, additionally checking for some known attack signatures. Find out more on the [Project's homepage](https://github.com/btoplak/Joomla-Anti-Malware-Scan-Script)
JAMSS output is very verbose and very useful, hover over any lines to see the details.

/com_radicalmart/site/src/Controller/DisplayController.php in line: 148
? Pattern found#17 - PHP: multiple encoded, most probably obfuscated code found
`					if (urldecode($current) != urldecode($redirect))`

**Comment by Septdir** [comment]
прогнал
