### ISSUE TITLE
[RM] Warning в списке товаров в админке

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#201]
`Warning: Undefined array key 0 in /var/www/fiction/www/mart.vm/administrator/components/com_radicalmart/src/Model/ProductsModel.php on line 422`

![2023-11-09_12-11-50](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/c1fcd509-6dbb-4a03-9c05-cd30af3d55a7)

**Comment by Septdir** [comment]
fixed
