### ISSUE TITLE
[RM] Двойное значение при выводе поля, значение которого содержит разделитель

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#202]
Характеристики. Selectbox. значения. Выбираю любое значение, в котором есть разделитель (запятая или точка - пробовал оба варианта)

<img width="762" alt="Снимок экрана 2023-11-10 в 10 17 00" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/8b1e0141-e733-4e81-9049-ab0183cd1ec1">

по факту выбрано одно значение.

на фронте получаю 2 значения на выдаче - предыдущее значение без разделителя и вот это:
<img width="672" alt="Снимок экрана 2023-11-10 в 10 21 42" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/46ea7230-f975-447e-bedc-c2bd7a1f871d">

если выбрать значение, не содержащее разделитель в виде точки или запятой, то выводится правильно - одно значение.
<img width="608" alt="Снимок экрана 2023-11-10 в 10 27 08" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/47048db7-84ca-4816-82e6-6ff9e19263c3">

**Comment by Sulpher** [comment]
смотрю в отладке:
                    [language] => *
                    [is_field] => 1
                    [rawvalue] => 16-5
                    [value] => 16, 16,5

тип: список
<img width="1359" alt="Снимок экрана 2023-11-10 в 10 44 09" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/a8eeed3c-c0d0-498a-a956-4eec35e5020e">

настройки:
<img width="1634" alt="Снимок экрана 2023-11-10 в 10 44 19" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/f71205a1-d6af-44ce-b548-94deb1b46ae8">

обрати внимание на дефис в значениях - может дело в этом?

**Comment by Sulpher** [comment]
Версия: 1.2.1-dev

**Comment by Septdir** [comment]
done
