### ISSUE TITLE
[RM-UIkit]  X товаров на строку и повторение grid

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#205]
Убрать рудимент BS. убрать `<hr>`. сделать по стандартам grid юикит.  можно добавить masonry

**Comment by Septdir** [comment]
`<hr>` - это разделитель. Он делает разделитель между рядами, создавая видимую сетку.
masonry - это совершенно другое. 
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/1588556a-fb12-4e51-9bda-327951c14235)

**Comment by Sulpher** [comment]
все правильно, я и имел ввиду masonry, тк высота блоков может отличаться. а так красиво смотрится.
