### ISSUE TITLE
[RM]  BS шаблон. не выводить стрелки если картинка одна

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#208]
<img width="1386" alt="Снимок экрана 2023-11-18 в 17 43 42" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/7fd5344b-66c1-447d-9141-6f8c98c1225b">

сделать проверку и если фото одно, то не выводить стрелки

**Comment by Septdir** [comment]
Верстка будет скакать когда вкладки переключаешь, так что в ядре нет
