### ISSUE TITLE
[RM] Категория. Сбрасывает параметр на неправильное значение после сохранения

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#209]
Настройка категории. Сортировка товаров.
По умолчанию значение - по новизне.
выбираю эту опцию и сохраняю - почему-то сбрасывает на "вручную".
если выбираю иное значение, например, недорогие, то при сохранении все в порядке.

вот выбираю значение по умолчанию:
<img width="1059" alt="Снимок экрана 2023-11-18 в 18 34 28" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/61ca0994-5c78-49cd-ad43-fc55afb18b2c">

после сохранения вижу вот так:
<img width="944" alt="Снимок экрана 2023-11-18 в 18 34 34" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/31fc6173-cc09-4adc-9905-9cd02c83f8d4">

radicalmart_1.2.2-dev, php 7.4, joomla 4.4.0

**Comment by Sulpher** [comment]
скринкаст:
https://www.dropbox.com/scl/fi/jyau06ka5q6h57j0n95yk/2023-11-18-18.35.34.mov?rlkey=vnvsigbqh0pe2bbx3csguqnul&dl=0

**Comment by Sulpher** [comment]
еще один баг такой же.

если создать пункт меню "Товары – Производитель", то по клику в предыдущие пункты он на себя тянет вьюшку, т.е. URL отличается, а вьюшка одна на все страницы категорий.
<img width="993" alt="Снимок экрана 2023-11-18 в 19 25 34" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/8612895a-43cc-4e24-adac-070c2ea4ad09">


radicalmart_1.2.2-dev, php 7.4, joomla 4.4.0

**Comment by Septdir** [comment]
Fixed
