### ISSUE TITLE
Скидки на товар

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#21]
предлагаю добавить раздел "скидки", где можно создать скидки, включающие в себя:
- название
- размер скидки
- процент или фиксированная сумма
- дата начала скидки/дата окончания скидки
- повторяющаяся скидка (когда таймер подойдет к концу, повторять)
предусмотреть выбор скидки как отдельным категориям (или всем категориям), так и внутри товара.

параметр "отображать countdown timer" в карточке товара: да/нет
это нужно на случай, если скидка будет ко всем товарам и нет смысла в карточке это выводить, тогда проще в шаблоне в позиции вывести общий модуль.

на фронте в карточке ниже коризины вывести таймер с отсчетом до конца скидки в стиле Uikit.

<img width="926" alt="Снимок экрана 2021-10-19 в 15 19 44" src="https://user-images.githubusercontent.com/3432048/137907863-08950470-2539-42ae-8cb3-53ad6b39c229.png">

https://getuikit.com/docs/countdown
добавить классы элементу, чтобы можно было кастомно оформить.

штука нужная, т.к. увеличивает конверсию продаж.

**Comment by Septdir** [comment]
Все скидки - это отдельное решение.
