### ISSUE TITLE
[RM] Пункт меню "категории - алфавитный указатеть" переопределяет другой пункт меню

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#212]
Я создал два пункта меню:
<img width="754" alt="Снимок экрана 2023-11-18 в 19 11 08" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/f778a29f-9517-44e1-86cc-9299a639924b">

в итоге на фронте у обоих пунктов меню ссылка ведет на алфавитный указатель. 
вот что получаю:
<img width="997" alt="Снимок экрана 2023-11-18 в 19 12 07" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/ea7724ea-d6f4-4b20-8ad1-1ffb692dc0ce">

если отключаю пункт меню алфавитный указатель, то сразу запускается список категорий:
<img width="915" alt="Снимок экрана 2023-11-18 в 19 12 16" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/a56952a3-d357-4bd2-9099-7f8fddf8bdfd">

сейчас не получается вывести два пункта меню с разными вьюшками категории.

radicalmart_1.2.2-dev, php 7.4, joomla 4.4.0

**Comment by Sulpher** [comment]
видео:
https://www.dropbox.com/scl/fi/5m8tojk6du60lnlgt0b5p/2023-11-18-19.17.19.mov?rlkey=r6k0ltnm8b74iih1fs90a7y4y&dl=0

**Comment by Sulpher** [comment]
еще один баг такой же.

если создать пункт меню "Товары – Производитель", то по клику в предыдущие пункты он на себя тянет вьюшку, т.е. URL отличается, а вьюшка одна на все страницы категорий.
<img width="993" alt="Снимок экрана 2023-11-18 в 19 25 34" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/8612895a-43cc-4e24-adac-070c2ea4ad09">


если я отключаю пункт меню "товары - производитель" и остается только "таблица товаров", она тоже переопределяет предыдущие пункты и когда в них переходишь, то вьюшка подключается таблицы товаров. 

в общем, баг в коде небольшой.

radicalmart_1.2.2-dev, php 7.4, joomla 4.4.0

**Comment by Septdir** [comment]
`сейчас не получается вывести два пункта меню с разными вьюшками категории.`
И не получится потому что - это дубль.
