### ISSUE TITLE
Стандартный плагин оплаты. Выдает Class "RadicalMartHelperPrice" not found

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#213]
Цитата:
В общем поставил этот плагин, активировал, привязал его к одному из способов оплаты.
При переходе из корзины на страницу оформления получаю ошибку "Class "RadicalMartHelperPrice" not found"

RM Версия: 1.2.0, Joomla 4.4.0, RadicalMart Payment: Стандарт - 1.0.0 (скачан с sovmart)

**Comment by Septdir** [comment]
RadicalMart Payment: Стандарт не поддерживается года 2 и не будет.

**Comment by Sulpher** [comment]
а как без него? бывают иногда случаи, когда нужна заявка на почту без онлайн оплаты.

**Comment by Septdir** [comment]
Просто делеаешь способ оплаты без плагина и все. или не делаешь способы оплаты вообще
