### ISSUE TITLE
[RM-UIkit] Заменить <a> на <button> в модуле корзины

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#214]
Суть:
<img width="1033" alt="Снимок экрана 2023-11-23 в 00 29 38" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/0083b139-6a5a-4bb8-92ab-767cefb7fea0">

**templates/yootheme/html/layouts/components/radicalmart/cart/icon.php:**

я заменил тег `<a>` на  `<button>`  и  добавил класс `uk-button uk-button-link`. получилось так:

`	<button radicalmart-cart="display_module" class="uk-link-reset radicalmart-icon uk-button uk-button-link" uk-tooltip>`

**Comment by Septdir** [comment]
Заодно блокировку button сделал и чтобы становилось ссылкой к корзине и оформлении заказа
