### ISSUE TITLE
[RME] Плагин для отправки Email

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#216]
Плагин для отправки email в лэйауте для RME фигурирует класс от РМ, как итог - фатал при оформлении заказа.

![2023-11-24_12-45-31](https://github.com/RadicalMart/Bug-Tracker/assets/17691519/6e7ab76a-1071-42bc-9c2d-0a6c33cb000c)

**Comment by Septdir** [comment]
Ура я наконец нашел это issue. Пофикшено!
