### ISSUE TITLE
[RM] Поля. Сворачивать сайдбар справа в режиме редактирования поля из товара

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#218]
а вот другая проблема. я хочу добавить еще одно значение, но не внизу, а там, где нужно. но из-за интерфейса приходится скроллировать влево-вправо. для этого гнать список вниз, пролистывать, нажимать на плюсик, потом я скроллю вниз и уже не видны названия полей, чтобы понять, куда перетащить выше. очень неудобно.  
предлагаемое решение: опционально сворачивать сайдбар справа.

видео в телеге:
https://t.me/c/1644266252/22858

**Comment by Septdir** [comment]
Модалка переназначена для быстрых правок sidebar в данном случае может быть важнее.
Чтобы перетаскивать, можно просто открыть поле в новой вкладке
