### ISSUE TITLE
[RM] Сделать отдельный макет списка товаров для производителей

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#22]
Группировка товаров по производителю при клике в карточке товара. нужен layout страницы с шапкой производителя и ниже его товарами.

в админке добавить соответствующий раздел.

**Comment by Septdir** [comment]
Раздела в админке не будет, а вот layout для производителей сделаем.

**Comment by Septdir** [comment]
Сделано
