### ISSUE TITLE
[RM] Меню - убрать два пункта если выбрано меню пользователя

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#220]
Настройки такие:
<img width="636" alt="Снимок экрана 2023-12-15 в 21 10 19" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/e5738086-76c1-4c7f-8c06-04759eb3a7bf">

а выводится вот так:
<img width="267" alt="Снимок экрана 2023-12-15 в 21 11 32" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/c14ce6a7-d742-4e66-bc45-d1af76aabf47">

первые 2 пункта подсветил - это выводится по умолчанию, а ниже уже пункты моего меню.
дело в том, что у меня меню в шапке в выпадашке выводится.

предлагаю не выводить эти два пункта, если выбрано меню пользователя.

**Comment by Septdir** [comment]
Меню - это именно дополнительное меню. Основное меняеться плагинами. Так что нет.
