### ISSUE TITLE
[RME-UIkit] Страницы Мои заказы и Мои данные - выставить единый отступ

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#221]
отступ до шапки отличается (высота).
вот страница заказы:
<img width="1265" alt="Снимок экрана 2023-12-17 в 10 16 23" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/4671a755-ab30-40e9-974c-9be851ea1afa">

отступ потому что:
uk-child-width-expand@m uk-grid-medium uk-grid

а вот страница мой профиль:
<img width="1265" alt="Снимок экрана 2023-12-17 в 10 16 31" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/7c00fdba-cfa4-4756-bb1d-9086924d6c6b">

здесь потому  что:
uk-child-width-expand@m uk-grid-medium uk-grid

предлагаю единый стиль сделать и взять за стандарт 2й вариант, тк когда кликаешь по пунктам, скачет высота при перезагрузке страницы. а когда отступ  меньше - то хорошо.

**Comment by Septdir** [comment]
У меня в чистом шаблоне одинковый отступ и классы одинаковые.
