### ISSUE TITLE
[RME-UIkit] Стандарты доступности. Мелкие правки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#222]
Google Pagespeed Insights.

**1. страница товара**
<img width="1014" alt="Снимок экрана 2023-12-18 в 10 14 27" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/acdf5304-1f8b-44bb-a3c6-b81ca352c2e5">
 Form elements do not have associated labels. Labels ensure that form controls are announced properly by assistive technologies, like screen readers.  https://dequeuniversity.com/rules/axe/4.7/label
ругается на поле для ввода кол-ва товара.

**2. страница категории.**
здесь два замечания.
ругается на пагинацию:
 Lists do not contain only <li> elements and script supporting elements (<script> and <template>). 
Screen readers have a specific way of announcing lists. Ensuring proper list structure aids screen reader output. [Learn more about proper list structure](https://dequeuniversity.com/rules/axe/4.7/list).
<img width="993" alt="Снимок экрана 2023-12-18 в 10 20 19" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/1e0f23de-6245-4713-aa48-2a36ab789979">
здесь вложенность li в li без ul:
<img width="917" alt="Снимок экрана 2023-12-18 в 10 27 52" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/15de27c9-a7be-4f75-a78a-32789ff68faf">

второе:
Select elements do not have associated label elements.
Form elements without effective labels can create frustrating experiences for screen reader users. [Learn more about the select element](https://dequeuniversity.com/rules/axe/4.7/select-name).
выпадающий список с выбором формата сортировки в компоненте (по дате, порядок ).
<img width="1004" alt="Снимок экрана 2023-12-18 в 10 21 40" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/a9df35e6-d795-4cb8-912a-058f25cd947d">

**Comment by Septdir** [comment]
По поводу стандартов доступоности. То отсутствующий label - это нормально.
По поводу пагинации в коде RM-UIKIT такого нет.
