### ISSUE TITLE
[RM] Админ.часть. не выводить список валюты, если одна валюта

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#223]
<img width="476" alt="Снимок экрана 2023-12-23 в 21 21 10" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/a1c05efa-2a90-4733-a711-857939878c41">

предлагаю просто отключать список, если валюта одна

**Comment by Septdir** [comment]
Пусть будет. Но я сделал что выводиться валюта по умочанию а не выбор валюты
