### ISSUE TITLE
[RM] Работа над оптимизацией категории >14 секунд загрузка

### ISSUE THREAD

**Issue by CB9TOIIIA** [RadicalMart/Bug-Tracker#224]
Простая страница категории - с отключенной сортировкой по in_stock

**Тяжелые запросы**

```
SELECT p.id,p.title,p.alias,p.code,p.category,p.categories,p.created,p.introtext,p.prices,p.stock,p.in_stock,p.shipping,p.fields,p.state,p.media,p.params,p.ordering,p.plugins,p.language,CAST(JSON_VALUE(p.prices, '$.rub.final') as double) as price
FROM `t889h_radicalmart_products` AS `p`
WHERE 
(`p`.`state` = :published) AND 
(FIND_IN_SET(678, p.categories))
ORDER BY p.ordering asc LIMIT 9
```

```
SELECT COUNT(*)
FROM `t889h_radicalmart_products` AS `p`
WHERE 
(`p`.`state` = :published) AND 
(FIND_IN_SET(678, p.categories))
```

![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/68e55a65-6b61-4dfb-bd87-792da1addd98)
![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/b67745bd-b57e-4097-b33a-7d5aa1830751)
![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/2d82d873-246f-4b14-b0e5-c667e1ba0556)

**Comment by Septdir** [comment]
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/c740719a-507a-419e-8a49-92d11093f22e)
Уже сделано
![изображение](https://github.com/RadicalMart/Bug-Tracker/assets/18382023/3c58ec46-add8-4426-9f7d-dec8a6ea528d)
