### ISSUE TITLE
[RM] Сделать кнопки для расчета мин/макс цен и МЕТА карточек и др. CRON комманд

### ISSUE THREAD

**Issue by CB9TOIIIA** [RadicalMart/Bug-Tracker#225]
Сейчас пришлось делать через shell_exec

![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/1adbe580-41bc-4de3-a7ea-982761f04f92)

Необходимо дать пользователю - менеджеру - управлять этим через "кнопки" или же автоматизировать.

![image](https://github.com/RadicalMart/Bug-Tracker/assets/1074710/c4014cfd-edd9-429c-b983-f5354d89035f)

**Comment by Septdir** [comment]
Готово
