### ISSUE TITLE
[RM] Модуль фильтр. Не подхватывает мин и макс значения цены из категории

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#226]
параметр цены в категории. указано от 20 000 до 70 000 руб. 
страница категории на фронте. модуль фильтра. там цены  - значение дефолтное от 0 до 200 000. значения в настройках категории не влияют на значения, выдаваемые модулем фильтра.

**Comment by Septdir** [comment]
Готово
