### ISSUE TITLE
[RM] Undefined index: sum_discount_string

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#227]
Дано: 
- RM 1.2.2dev (выдан в конце декабря)
- плагина скидок и купонов нет
- пыха 7.4

**AH01071: Got error 'PHP message: PHP Notice:  Undefined index: sum_discount_string in /var/www/site.ru/templates/yootheme_styling/html/com_radicalmart/cart/default.php on line 198 ', referer: https://site.ru/kursy/osnovnoj-kurs**

198  строка:
`<?php echo $product->order['sum_discount_string']; ?>`

полный код:

```
<?php if (empty($product->order['discount_enable'])) echo 'style="display:none"'; ?>>
<s radicalmart-cart-display="products.<?php echo $p; ?>.order.sum_base_string">
<?php echo $product->order['sum_base_string']; ?>
</s>
		( - <span
			radicalmart-cart-display="products.<?php echo $p; ?>.order.sum_discount_string">
		<?php echo $product->order['sum_discount_string']; ?>
		    </span>)
</div>
<div class="uk-text-nowrap uk-text-bold"
		radicalmart-cart-display="products.<?php echo $p; ?>.order.sum_final_string">
        <?php echo $product->order['sum_final_string']; ?>
</div>
<?php endif; ?>
```

у этого товара нет скидки:
<img width="729" alt="Снимок экрана 2024-01-02 в 13 11 16" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/3b1f9a94-3847-4b0d-8cfb-73180e1a3dd4">

**Comment by Septdir** [comment]
done
