### ISSUE TITLE
[RM] обращение к строке как к объекту

### ISSUE THREAD

**Issue by nekrasovvitaliy** [RadicalMart/Bug-Tracker#228]
components/com_radicalmart/tmpl/order/default.php

в строке 165 $field становится string, а в 177 к нему обращение как к объекту

![image](https://github.com/RadicalMart/Bug-Tracker/assets/16386994/7b5225ae-a295-4b97-a1a9-71f05897d744)

измените строку 165-166 на
								$fieldInput = $this->form->getInput($field->fieldname, $field->group);
								if (empty($label) && empty($fieldInput))

**Comment by Septdir** [comment]
done
