### ISSUE TITLE
Добавить раздел Группы покупателей

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#23]
Ввести параметр "группа по умолчанию для нового покупателя"

Для чего нужно?
по умолчанию, registered users попадают в группу покупателей default.
но в последствии можно гибко управлять правами и сделать довесок:

Default
Silver 
Gold 

соответственно, в настройках можно связывать скидки с группами пользователей. 
и даже сделать доп. аддон "назначать в группу в зависимости от суммарных покупок". купил на 50 тыс. руб. - перешел в группу Silver с 5% скидкой на все товары. и т.д.
или вешаем оплату членства в клубе -купил членство и был назначен в новую группу пользователей навсегда. (это отдельная тема, на будущее)

но пока нужно архитектурно предусмотреть группы пользователей.

**Comment by Septdir** [comment]
Не вижу смылса делать это в ядре. А как отдельный плагин связать с группами joomla можно.
