### ISSUE TITLE
[RM] Пересчёт мин, макс цены для товаров (мета, категорий) с учётом скидок

### ISSUE THREAD

**Issue by pakimov** [RadicalMart/Bug-Tracker#232]
Предлагаю добавить дополнительно в cli команду для пересчёта минимальной и максимальной цены с учётом скидки. Сейчас скидка не учитывается и в значения записывается базовая цена.

**Comment by Septdir** [comment]
Надо добавить параметр какую цену товара брать для калькуляций 
Заодно переделать калькуляцию цен при save
