### ISSUE TITLE
[RM-Fields-Standard] Редактирование товара. Один параметр на строку

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#235]
<img width="701" alt="Снимок экрана 2024-02-02 в 15 11 37" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/fc8d6d7b-474c-4de9-ab92-b6b97f28cff1">
предлагаю в админке в одну строку выводить значение параметров

иначее неудобно -  начинаешь по списку искать нужное значение и сбиваешься. 
удобно, когда один параметр на строку

**Comment by Septdir** [comment]
Сделал в новом RM заработает
