### ISSUE TITLE
[RM] Снятый с публикации мета-товар отображается

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#236]
отключил мета-товар и его товары.
на фронте иду в категорию (тип отображения - мета-товары) и гостем вижу этот товар доступным в списке.

**Comment by Septdir** [comment]
https://github.com/RadicalMart/Bug-Tracker/assets/18382023/a94c6118-2fe1-4f27-8c3c-45c9abd3977f
