### ISSUE TITLE
[RM] Админ. Выпадающий список категорий сделать шире

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#237]
<img width="1910" alt="Снимок экрана 2024-02-05 в 13 07 37" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/b2a85d36-c346-467f-972f-2ed0843071aa">

список узкий, а справа куча места. если это не ограничение админки J, может сделаем шире список категорий?

**Comment by Septdir** [comment]
Сделал
