### ISSUE TITLE
[RM] Админ. При очистке фильтра сортировка товаров не меняется

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#238]
Вот фильтр: я выбираю сортировку товаров по конкретной категории.
это срабатывает.
<img width="1584" alt="Снимок экрана 2024-02-05 в 13 40 57" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/2a24dc92-24f5-43f1-afce-ce72334b5643">

но если нажму на кнопку очистить (убрать фильтрацию по конкретной категории), то в списке категорий значение убирается на "выбор категории", но логика не срабатывает - все те же товары категории выводятся.
 нужно нажать на иконку крестика и только тогда сортировка отменяется и мы видим все товары.

<img width="1538" alt="Снимок экрана 2024-02-05 в 13 41 05" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/a6458e9d-7979-4c8d-8d15-113ef6a5b860">

**Comment by Septdir** [comment]
Теперь работает
