### ISSUE TITLE
Метрическая/имперская система мер

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#24]
Взят готовый набор. Можно дополнить по умолчанию:

Size Unit (размеры)
 - Millimeter
 - Centimeter
 - Inch (дюйм)
 - Foot (фут)

Weight Unit (вес)
 - Gram
 - Kilogram
 - Pound (фунт)
 - Ounce (унция)

Volume Unit (объем)
 - Milliliter (миллилитр)
 - Centiliter (сантилитр)
 - Liter (литр)
 - Pint (пинта)
 - Quart (кварта)
 - Gallon (галлон)
 - Ounce (унция)

**Comment by Septdir** [comment]
Добавил размеры и вес.
Будут в сл. релизе.
Что до объема то вес и размеры используются для доставки, а отсальное ты можешь сделать либо доп полями либо плагином.
