### ISSUE TITLE
[RM] Сайт. Ошибки validator.w3 в подключении скриптов (defer type=module) 

### ISSUE THREAD

**Issue by MSGroupFM** [RadicalMart/Bug-Tracker#240]
Валидатор ругается на ошибки в подключении скриптов RadicalMart. Элемент скрипта с type="module" не может содержать атрибут defer.

> A script element with a defer attribute must not have a type attribute with the value module.

`<script src="/media/com_radicalmart/js/trigger.min.js?fa7a84a4c212f9eeb97fa050dfa6a559" defer type="module">`

**Comment by Septdir** [comment]
Не принципиально
