### ISSUE TITLE
[RM] Удалить CSRF из текста страницы

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#242]
удалить упоминание CSRF на всех страницах магазина
<img width="2503" alt="изображение" src="https://github.com/RadicalMart/Bug-Tracker/assets/3103677/530039da-db1a-4a66-8e37-b31c33d542f2">

**Comment by Septdir** [comment]
Заодно убрать устаревшую установку js параметров и переименовать параметры с `radicalmart_settings` на `radicalmart.settings`
