### ISSUE TITLE
[RM] Разрешить ввод запятой в качестве разделителя числа

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#246]
В некоторых странах в качестве разделителя в ценах используется запятая вместо точки.
сейчас невозможно ввести запятую, только точку.

<img width="699" alt="Снимок экрана 2024-02-22 в 23 16 06" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/64a0d7d2-621c-4e4b-a35b-364ffe98e2b2">

на будущее магазин расширять на внешний мир, нужно учитывать.
юзеры из таких стран не догадаются ввести точку или будет неудобно.

можно сделать подмену запятой на точку при вводе? 

упс. загуглил. оказывается, в нашей стране как раз такой стандарт:

_В Российской Федерации для разделения целой и дробной (десятичной) частей числа принято использовать запятую. Именно об этом написано в ГОСТ 2.307-2011 и ГОСТ Р 21.1101-2013. ГОСТ 2.004-88 допускает использование точки в качестве разделителя, но это допущение._

одновременное применение запятой и точки в качестве разделителя не допускается. 

https://www.normacs.info/answers/1570

**Comment by Septdir** [comment]
Предусмотрено в настройках валюты

**Comment by Sulpher** [comment]
может  по умолчанию в настройках магазина для рубля поставить запятую в след.версии? стандарт для РФ все таки.
это затронет уже работающие магазины?

**Comment by progreccor** [comment]
> может по умолчанию в настройках магазина для рубля поставить запятую в след.версии? стандарт для РФ все таки. это затронет уже работающие магазины?

несмотря на то, что стандартом является запятая, в реальности в компьютерах все привыкли к точке. Как пример - ты даже не знал про это.
Поэтому менять на запятую по умолчанию - поломать пользовательский опыт всем и  всем будет казаться что магазин не работает.
Лучше не трогать. 
кому надо - поменяет сам
