### ISSUE TITLE
Добавить настройки в способ оплаты

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#25]
Выставление статуса заказа: - параметр - и в выпадающем списке значения из "статусы заказа"

Статус по умолчанию - выбираем из списка. 
это подойдет для простого плагина по умолчанию.

Для кастомных плагинов оплаты параметры расширяются до:

Completed Status
Failed Status
Pending Status
Cancelled Status
Refunded Status
и т.д. 

вообще такой набор зависит от требований платежного плагина и будет отличаться, так что это на откуп разработчикам. 

еще нужно добавить в настройках способ оплате поле "цена". иногда это нужно.

**Comment by Septdir** [comment]
Это делаться непосредственно в плагине оплаты. К примеру это есть в плагине CloudPayments
