### ISSUE TITLE
[RM] Плагин интеграции с Telegram. Передавать комментарий к заказу

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#251]
На странице оформления заказа есть поле "комментарий к заказу". 
его содержимое не передается в телегу. 
предлагаю это сделать. будет полезно.

**Comment by Septdir** [comment]
Это можно сделать в переопределении. В "ядре" смысла не вижу, потому что кто-то использует это поле как служебное.
