### ISSUE TITLE
[RM-UIkit] Добавить авторизацию в checkout для гостя

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#256]
Страница оформления заказа. нужно гостю перед списком заказов вывести сообщение с ссылкой:
`"У вас уже есть аккаунт? <a>Авторизуйтесь на сайте</a>"`

это важно для тех, у кого уже есть аккаунт на сайте, но они начали оформлять заказ гостем и нужно авторизоваться.

**Comment by Septdir** [comment]
Есть режим оформления заказа, доступный только зарегистрированным. Тогда он будет спрашивать есть ли аккаунт и предлагать зарегистрировать.
