### ISSUE TITLE
[RM] Убрать ?start=0 из ссылка на первую страницу категории в пагинации

### ISSUE THREAD

**Issue by alex-revo** [RadicalMart/Bug-Tracker#261]
![image](https://github.com/RadicalMart/Bug-Tracker/assets/7030604/d75084f8-c25a-4a22-b82c-71cd97f2c03f)

Сейчас она дает 301 редирект для каждой категории.

**Comment by Septdir** [comment]
Это родная пагинация joomla, туда не полезем. 301 ее закрывает. А что совсем не было можно переопределить постраничный навигацию в шаблоне
