### ISSUE TITLE
[RM] Добавить meta name="robots" в типы пунктов меню для Корзины и Личного кабинета

### ISSUE THREAD

**Issue by alex-revo** [RadicalMart/Bug-Tracker#262]
Для этих типов страниц:
![image](https://github.com/RadicalMart/Bug-Tracker/assets/7030604/1bac1085-0e45-4576-a8cb-a7d3a9c9e704)

Не хватает на вкладке SEO параметра
![image](https://github.com/RadicalMart/Bug-Tracker/assets/7030604/640f2eb6-aa35-4e0b-9df3-95a3a1dd9260)

Это позволит закрывать индексацию служебных разделов из меню.

**Comment by Septdir** [comment]
Она там стоит noindex follow У скрытых и лк.
