### ISSUE TITLE
[RM] Бейджи. Сбрасываются 2 значения параметров отображения

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#268]
ставлю значения отображения на скрыть:
<img width="1405" alt="Снимок экрана 2024-07-09 в 12 09 53" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/82318b74-3d66-459b-a867-9ad4776fbb33">

они сбрасываются после сохранения:
<img width="1462" alt="Снимок экрана 2024-07-09 в 12 11 47" src="https://github.com/RadicalMart/Bug-Tracker/assets/3432048/5a74e173-4fba-492e-94b8-ca0e3d0fb4cd">

RM Версия: 2.1.1

**Comment by fiction13** [comment]
Подтверждаю, Что выводить тоже сбрасывается.

@Septdir Скажи, куда копнуть, я хоть локально поправлю у себя.

**Comment by fiction13** [comment]
Параметры в $data не попадают при сейве категории.

**Comment by Septdir** [comment]
Смотреть надо сначала имя полей, потом смотреть как отрпаляеться  и т.д
Завтра гляну то напомните

**Comment by Septdir** [comment]
Это плгаин связанных товаров
