### ISSUE TITLE
Создание нового поля при редактировании товара

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#27]
Собственно, вот:
<img width="710" alt="Снимок экрана 2021-10-22 в 11 17 41" src="https://user-images.githubusercontent.com/3432048/138419399-2eda70c2-22f7-4126-a9fe-83679cb3817f.png">

есть товар, ручка. два цвета: белый и красный. в полях нет нужного значения. 
для этого нужно выйти из режима редактирования товара, добавить новое значение в полях и вернуться. 

нужна возможность создания значения в режиме редактирования товара (например, добавить элемент плюсик и модальное окно для быстрого создания)

**Comment by Septdir** [comment]
В стандартных полях этого не будет. Причина тут просто. Любовь менеджеров копипастить значения и нажимать enter. Та что чтобы не было как на скриншоте, я не вижу смысла этого делать.
![изображение](https://user-images.githubusercontent.com/18382023/141982039-96a13f07-11dc-4c6e-bcbd-b1558cb650cd.png)

Но ни кто не запрещает сделать свои поля, где это будет.
