### ISSUE TITLE
[RM] Создать в товаре поле для хлебных крошек (для адресов без категорий)

### ISSUE THREAD

**Issue by progreccor** [RadicalMart/Bug-Tracker#270]
Рассматриваем вариант когда главная категория товара привязана к главной странице и таким образом адреса  товаров существуют без категорий.

В этом случае нам нужно корректно указать хлебные крошки, которые бы содержали нужные нам категории. Поскольку для этого главная категория не подходит, есть предложение ввести специально поле для указания категории для хлебных крошек.

Если это поле заполнено, тогда хлебные крошки должны формироваться на основе указанной категории, а не на основе главной категории товара.

**Comment by Sulpher** [comment]
в данном случае придется делать модуль хлебных крошек РМ? ведь стандартный модуль Joomla не будет учитывать доп.поле.

**Comment by Septdir** [comment]
готово. модуль стандартный будет работать. Да и кастомные навреное тоже.
