### ISSUE TITLE
[RM] Админка. Полоса прокрутки если много категорий выбрано к показу в поле

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#271]
<img width="2137" alt="Снимок экрана 2024-07-31 в 17 54 33" src="https://github.com/user-attachments/assets/3e0d78fd-eeb1-41ac-853d-23d1fa01cb58">

накидал в каких категориях отображать поле.
итого появилась горизонтальная полоса прокрутки. 
особенность Joomla или пришаманить перенос строк можно через bootstrap?

**Comment by Septdir** [comment]
Не знаю у меня преносится
