### ISSUE TITLE
[RM] Шаблон письма о заказе: уточнить, что доставка - услуга

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#273]
способ доставки выводится ниже товара. 
<img width="1609" alt="Снимок экрана 2024-08-14 в 21 23 41" src="https://github.com/user-attachments/assets/cb2058bb-f89c-480d-96a0-100ac28eeaa3">

предлагаю отдельной таблицей сделать и назвать ее «услуга» / доставка
либо заголовок таблицы выше назвать как товар/услуга

**Comment by Septdir** [comment]
Доставка не всегда услуга. И заголовок у нее разные. Сделать как нужно можно переопределении.
