### ISSUE TITLE
[RM] Удалять заказы со статусом Новый или менять статус спустя указанное время

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#274]
Сабж. Может накопиться множество таких заказов. Кто-то просто посмотрел, будут ли скидки или применяются ли купоны и не планировал именно такой товар оплачивать, а в заказах будет висеть как "новый".

удалять такие заказы спустя N дней или менять статус на "отменен". 
можно опции предусмотреть.

похожая задача:
https://github.com/RadicalMart/Bug-Tracker/issues/16

**Comment by Septdir** [comment]
Можно сделать cli скрипт если нужно.
