### ISSUE TITLE
Ресайзинг, обработка изображений, хранение файлов

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#28]
Сейчас отсутствует обработка изображений. Картинки вставляются как есть:

`<img src="/images/Pen.jpg" alt="Фирменная ручка" class="uk-height-max-medium">`

нужно ввести параметры для указания размеров для мини-эскиза, среднего эскиза и, возможно, большого изображения. также указывать размер изображений категории.
отсутствует обработка названий файлов. (Pen.jpg)

загрузчик нужно переписать, добавив обработчик изображений вместо вызова списка картинок.

для созданных картинок нужно выделить специальную папку.

два режима обработки на выбор: GD2 и Imagemagick

**Comment by Septdir** [comment]
Обработка изображений полностью зависит от сайта. То бишь ни каких авто созданий эскизов в компоненте не будет. 
Но будет внешний сервис, который позволит все это сделать.

В самом же компоненте есть `RadicalMartHelperMedia::findThumb` в метод можно передавать и папку и префикс по умолчанию префикс `thumb__` то бишь если рядом с исходным файлом будет лежать файл `thumb__ИМЯ ФАЙЛА` то будет выводится thumb. 
И опять-таки можно передавать свои параметры и при помощи верстки сделать так как нужно на конкретном сайте.
