### ISSUE TITLE
[RM] Тяжело менять статус заказа на мобилке

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#283]
Понимаю, что админка в принципе не сильно удобна под мобилку. Но раньше, когда был листбокс, можно было относительно удобно править статус заказа с телефона. Сейчас это заметно усложнилось за счёт очень узкого контейнера. Быть может, можно поменять вёрстку окна смены статуса заказа под мобилку?

![photo_2024-10-03_11-28-56](https://github.com/user-attachments/assets/ac2bb93d-99ee-44da-a068-b5d97558299c)

**Comment by Septdir** [comment]
Это баг по не досмотру. Если честно я даже не проверил.
