### ISSUE TITLE
[RM] PHP Warning:  Undefined property. Конфиг магазина

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#285]
Обновил Joomla до 5.2.0. А RM уже 2.2.0. PHP 8.3.8
в логах:

`[Mon Oct 21 12:07:26.117828 2024] [proxy_fcgi:error] [pid 3840648:tid 3840705] [client 95.25.123.213:37668] AH01071: Got error 'PHP message: PHP Warning:  Undefined property: Joomla\\CMS\\Table\\Extension::$module in /var/www/www/.ru/plugins/actionlog/joomla/src/Extension/Joomla.php on line 536', referer: https://.ru/administrator/index.php?option=com_config&view=component&component=com_radicalmart&path=&return=aHR0cHM6Ly9kZXYuc3R1ZGlvbS1yaXR1YWwucnUvYWRtaW5pc3RyYXRvci9pbmRleC5waHA%2Fb3B0aW9uPWNvbV9yYWRpY2FsbWFydCZ2aWV3PWNhdGVnb3JpZXM%3D`

хм. actionlog плагин?

**Comment by Septdir** [comment]
Да это не ошибка РМ
