### ISSUE TITLE
[RM] Нижняя прокрутка в полях

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#290]
![image](https://github.com/user-attachments/assets/1b54ed4a-1bd0-4c45-a263-5293d20c5b7c)

Не видно пагинации, неудобный вид.

**Comment by Sulpher** [comment]
я тоже столкнулся с этой проблемой. и даже не заметил прокрутку, думал, что поля исчезли, тк пагинация уехала направо.
