### ISSUE TITLE
[RM] Показать дополнительные поля в корзине

### ISSUE THREAD

**Issue by Mitriy-Bug** [RadicalMart/Bug-Tracker#299]
Хотелось бы иметь возможность выводить нужные поля в модуле корзины, на странице корзины
![22-12-2024 22-50-02](https://github.com/user-attachments/assets/378a9083-a900-4eeb-8007-e5a8f14e29f8)

**Comment by Septdir** [comment]
Такая возможность есть.
Описано тут
https://github.com/RadicalMart/Bug-Tracker/issues/157
