### ISSUE TITLE
[RM] RadicalMart Payment: Стандарт - ОШИБКА

### ISSUE THREAD

**Issue by Mitriy-Bug** [RadicalMart/Bug-Tracker#301]
RadicalMart Payment: Стандарт 
выдает ошибку подключения класса
![23-12-2024 15-01-33](https://github.com/user-attachments/assets/4b49e623-9580-4f1d-a9a8-38e51e295126)
![23-12-2024 15-04-12](https://github.com/user-attachments/assets/bb6cb07f-3e8d-4244-9f2f-0dd78b12fecb)

**Comment by Septdir** [comment]
Этот плагин уже давно не поддерживается. Удаляйте его он не нужен. Если вам просто надо создать способ оплаты можно не выбирать плагин.
