### ISSUE TITLE
Параметры вывода кол-ва товаров - на строку и на страницу

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#31]
Добавить параметры в админку: 

- кол-во товаров на строку (можно списком с заданными значениями. 3,4,5,6) 
- кол-во товаров на страницу

учитывать при пагинации.

**Comment by Septdir** [comment]
Не вижу в этом смысла. Компонент написан по канону и его очень лего переопределять. А лишние настройки ни только перегрузят админской интерфейс, но и превращают верстку в ад.
P.S Каждый раз верстка JShopping VM и hika начинаться с вырезания этих параметров из макетов.
