### ISSUE TITLE
Корзина (оформление заказа) - баг верстки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#33]
Баг в верстке.
<img width="1280" alt="Снимок экрана 2021-10-26 в 22 19 49" src="https://user-images.githubusercontent.com/3432048/138946700-518ff79f-d35f-4005-ad6f-702875dfba22.png">

**Comment by Septdir** [comment]
Баг по фиксил, что касается второго, да это надо добавить кастомный код для шаблона.
Можно сделать на css Ориентируясь на атрибут `aria-invalid="false|true"`
