### ISSUE TITLE
Корзина (оформление заказа) - добавить чекбокс согласия с правилами

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#34]
Нужно добавить возможность согласия с правилами сайта и с политикой конфиденциальности. Это обязательно.
Также добавить тригер для подписки на рассылку (чекбокс) - это опционально. можно потом плагином сделать.

В настройках магазина выбирать связь с материалами политики конфиденциальности и договора-оферты.
учесть мультиязычность и выбор для каждого активного языка.
можно сделать вкладками параметры каждого языка. если нужен пример - напишите.

тут сважный момент - пользователь должен согласиться с правилами сайта для финализации платежа.
можно это сделать опционально. но для 152-ФЗ такая штука нужна.

**Comment by Septdir** [comment]
#54
Сюда же
