### ISSUE TITLE
У вас нет прав доступа - после авторизации

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#37]
я - гость. добавил товар в корзину. нажал на "оформить заказ".
далее вижу, что я - гость. нажимаю на пункт меню  "войти" (com_login). 
после авторизации возвращаюсь на страницу оформления заказа и получаю:
<img width="736" alt="Снимок экрана 2021-10-27 в 18 12 17" src="https://user-images.githubusercontent.com/3432048/139094601-5a7578a3-094a-40fc-8d1f-0b36788f4cfe.png">

после авторизации должно без проблем возвращать обратно на оформление заказа.

**Comment by Septdir** [comment]
Не могу повторить.
Случаем у пукнта меню checout права доступа не стоят?

**Comment by Sulpher** [comment]
это не проблема магазина.  верхнее меню 
здесь два пункта:

войти - guest
выйти - registered

когда я сейчас пытаюсь войти, то система кидает на тот же пункт меню, где и был - на guest и возникает ошибка

Решение:
Пункт меню вход и выход скрытые public
а потом делаешь псевдонимы и вот им уже делаешь доступы
