### ISSUE TITLE
Иконки платежных систем не отображаются на checkout

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#38]
иконка:
<img width="509" alt="Снимок экрана 2021-10-27 в 18 15 08" src="https://user-images.githubusercontent.com/3432048/139095129-111042f4-24b4-46ec-bc52-fa4762e51d17.png">

иконка не отображается:
<img width="727" alt="Снимок экрана 2021-10-27 в 18 15 54" src="https://user-images.githubusercontent.com/3432048/139095191-02d74a54-097d-4f85-9dd1-2136dba765fe.png">

нужно выводить иконку платежной системы, это красиво смотрится и ассоциируется лучше с определенными платежными системами.

**Comment by Septdir** [comment]
Сделано
