### ISSUE TITLE
Меню администратора: Notice: Undefined index: COM_RADICALMART

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#40]
Создал меню типа Administrator
при переходе и попытке создать пункт меню, ошибка
<img width="1075" alt="Снимок экрана 2021-12-03 в 12 53 39" src="https://user-images.githubusercontent.com/3432048/144583018-516773e9-8266-4aa1-9dde-b83a50b5868e.png">

```
Notice: Undefined index: COM_RADICALMART in /var/www/www/plugins/system/radicalmart/radicalmart.php on line 155
Warning: Invalid argument supplied for foreach() in /var/www/plugins/system/radicalmart/radicalmart.php on line 155

```
такой ошибки нет в меню типа Сайт.
RadicalMart 0.3.0

**Comment by Septdir** [comment]
https://github.com/RadicalMart/Bug-Tracker/issues/51
Сделано
