### ISSUE TITLE
Оформление заказа - отсутствует возможность изменить данные

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#42]
Оформление заказа.
заполняю поля, выбираю способ оплаты, доставки, нажимаю на "оформить заказ" - выводится финальная страница, на которой отображаются все значения и нужно подтвердить действие, снова нажав на "оплатить".

проблема в том, что нет возможности вернуться на предыдущий шаг. а это важно: мы смотрим превью и нужно что-то изменить, но такой возможности нет. переход по хлебным крошкам приводит к тому, что заказ получает статус "создан" и его пользователь не может изменить.

и на финальной странице  есть  мелкий баг верстки:
<img width="1236" alt="Снимок экрана 2021-12-12 в 14 31 00" src="https://user-images.githubusercontent.com/3432048/145712225-783e0b8e-86a6-4667-8e36-f95f237caf4d.png">

**Comment by progreccor** [comment]
что касается "бага" верстки - это зависит от настроек твоей темы
судя по скрину - выставлено большое расстояние  между буквами. это настраивается в теме

**Comment by Sulpher** [comment]
> что касается "бага" верстки - это зависит от настроек твоей темы судя по скрину - выставлено большое расстояние между буквами. это настраивается в теме

на сайте чистый Yootheme pro без кастомизации стилей и Радикал из коробки. ничего не переопределял. layout этой страницы идет в комплекте с продуктом.

**Comment by progreccor** [comment]
> > что касается "бага" верстки - это зависит от настроек твоей темы судя по скрину - выставлено большое расстояние между буквами. это настраивается в теме
> 
> на сайте чистый Yootheme pro без кастомизации стилей и Радикал из коробки. ничего не переопределял. layout этой страницы идет в комплекте с продуктом.

"чистого" yootheme pro не бывает. у тебя выбрана какая то тема уже. 
угадывать за каждого какие кто сделает настройки - невозможно. тащить свои настройки на каждый чих - это противоречит начальному предназначению радикалмарт. 
тем более что я явно вижу - не включены настройки Cyrillic для шрифтов.

**Comment by Sulpher** [comment]
> у тебя явно чересчур большое расстояние между символами

точно. letter-spacing: 2px для .uk-text-meta. убрал в отладчике, теперь красиво.
<img width="380" alt="Снимок экрана 2021-12-12 в 15 45 53" src="https://user-images.githubusercontent.com/3432048/145712881-2c45058d-3601-45e5-91a3-caa87e2ae87d.png">

**Comment by Sulpher** [comment]
еще момент: 
система запоминает значение в text-area:
<img width="970" alt="Снимок экрана 2021-12-12 в 21 52 39" src="https://user-images.githubusercontent.com/3432048/145725583-68643177-fc59-47f5-a8e9-aae2a946ca91.png">

удобно, что поля с ФИО/телефоном и адресом система помнит. но поле комментарий к заказу нужно очищать. 
у меня в каждом тестовом платеже перекочевывает этот коммент.

**Comment by Septdir** [comment]
Там теперь есть сообщения об офоремении заказа и страница благодарности. Что до хлебных крошек. можно оформление заказа вложить в корзину, либо сделать кнопку вернуться в корзину при верскте
