### ISSUE TITLE
Сообщение success после успешной оплаты

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#43]
![124](https://user-images.githubusercontent.com/3432048/145712665-8c3b5da5-1c4e-4420-b095-2bf22e3983ce.png)

так и должно быть? 
ожидается сообщение об успешном заказе в рамках шаблона сайта, а здесь голый html без оформления.

еще опечатки в сообщении.

**Comment by Septdir** [comment]
Так и должно быть. Саму страницу можно переопределить в шаблоне добавив туда позиции и т.д
Ну а содержимое страницы может даже платежный плагин.

Опечатки пришли.

**Comment by Sulpher** [comment]
_Если перенаправление не происходить передите по ссылке_

правильно:
`Если перенаправление не происходит, перейдите по ссылке`

насчет таймера отчета: можно заморочиться и падежи добавить (1 секунда, 3 секунды, 5 секунд),  но это необязательно.

**Comment by Septdir** [comment]
Поправил опечатки в константах.
`COM_RADICALMART_PAYMENT_PAY_PAGE_DESCRIPTION`
`COM_RADICALMART_PAYMENT_SUCCESS_PAGE_DESCRIPTION`

>можно заморочиться и падежи добавить (1 секунда, 3 секунды, 5 секунд), но это необязательно.
Этого делать не буду. Там JS и это не очень удобно.

Вообще можно по желанию переделать страницу так чтобы редирект был, только после смена статуса заказа.
