### ISSUE TITLE
Уведомления на email

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#44]
<img width="988" alt="Снимок экрана 2021-12-12 в 18 01 22" src="https://user-images.githubusercontent.com/3432048/145718379-b41da1c7-cdd1-4d89-b0dd-725f5f6f5150.png">

1. ссылки в письме некликабельные
2. указана общая стоимость. не отображается отдельной строкой доставка. нужно сделать.
3. слово комиссия сбивает с толку. первый вопрос: "комиссия за что?" это берется из плагина стандартной оплаты (указал цену в 50 руб)
4. Сама фраза "До скидки" подразумевает скидку, а её нет.

**Comment by Sulpher** [comment]
допишу:  формировать ссылку на товар/заказ с учетом ЧПУ.

**Comment by Sulpher** [comment]
В Joomla 4 есть фича переопределения шаблонов писем. хорошо бы потом подтюнить, чтобы можно было это письмо кастомизировать.

**Comment by Sulpher** [comment]
я сформировал и оплатил заказ. на email как клиент получил уведомление.
<img width="981" alt="Снимок экрана 2021-12-12 в 21 44 05" src="https://user-images.githubusercontent.com/3432048/145725298-20442e6e-d619-4bd7-add9-2989eec956ed.png">
здесь есть кнопка оплатить. 
нажимаю на нее (я уже ранее оплатил заказ) и получаю:

404
Оплата не доступна

URL: https://domain.ru/radicalmart_payment/pay/000261212

нужно или убрать ссылку оплаты или сделать проверку - если платеж совершен, то кидать на список заказов.

**Comment by Septdir** [comment]
Стоимость доставки добавил.
![изображение](https://user-images.githubusercontent.com/18382023/163815651-92cbc241-c948-40dc-92e4-e18963658dd0.png)
Ссылки на товары по фиксил.
Кнопку оплатить пофиксил.

**Все выйдет со следующей версией плагина email**

Сами шаблоны писем - это layout так что можно переопределить.
Насчет шаблонов из Joomla 4 будем думать когда перейдем.
