### ISSUE TITLE
Плагин стандартной оплаты. перекидывать после оплаты

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#45]
Выбираю стандартный плагин оплаты, подтверждаю заказ.

на финальном этапе выводится информация для проверки, но нет кнопки "оплатить" и заказ получает статус "новый".
это выглядит как незавершенное действие.
предполагается, что по нажатию на кнопку "оплатить" (ее нужно вывести) с учетом такого плагина, нужно перекинуть юзера на страницу об успешной оплате/заказе.
можно добавить поле для URL в настройках плагина.

**Comment by Septdir** [comment]
Фактически стандартный плагин оплаты - это рудимент. Наверное его и вовсе потом удалим. Ибо способ оплаты можно создавать и без плагина вообще
