### ISSUE TITLE
В случае неуспешного платежа перекидывает на страницу "спасибо за оплату"

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#46]
В работе плагин эквайринга Сбербанка.

Специально тестируем неудачный сценарий: тестовая карта с неправильным 3d secure.
<img width="549" alt="Снимок экрана 2021-12-12 в 22 32 15" src="https://user-images.githubusercontent.com/3432048/145781899-f5c6ab56-8ebe-40de-a4f1-5d09dadf1bb7.png">

после 3й неудачной попытки оплаты кидает вот сюда:
<img width="1448" alt="Снимок экрана 2021-12-12 в 22 32 34" src="https://user-images.githubusercontent.com/3432048/145782093-dde63cf9-cfee-4fb2-bc5b-fa7d2d8cadb0.png">

обращаю внимание на URL:
там есть слово error. однако кидает на страницу успешной оплаты.
потом возвращает обратно на страницу финализации заказа:

<img width="1246" alt="Снимок экрана 2021-12-12 в 22 25 02" src="https://user-images.githubusercontent.com/3432048/145782503-00df0947-6553-4d2d-a3c6-f15ba96e4b8d.png">

и если еще раз нажать на "оплатить", то получаем:
<img width="946" alt="Снимок экрана 2021-12-12 в 22 18 35" src="https://user-images.githubusercontent.com/3432048/145782526-e0653bde-f3bb-46d5-9c3c-5c55b6310d73.png">

при неудачной оплате нужно возвращать обратно куда-то на сайт и очищать корзину.

**Comment by Septdir** [comment]
Фикс error `/components/com_radicalmart/controllers/payment.php` ~289
Должно быть return $this->page('error');

В 1.0 поправил
