### ISSUE TITLE
Сбрасывается сессия пользователя при возврате в магазин

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#47]
Я разобрался, отчего сбрасывается сессия после возврата в магазин.

итак, после успешной оплаты перебрасывает на страницу с благодарностью, где есть ссылка для перехода и таймер  обратного отсчета.

![2021-12-13 23 13 55](https://user-images.githubusercontent.com/3432048/145881800-6a4665ba-1b6a-4480-bea5-1dc7bb4334d4.jpg)

если ничего не делать и секунды истекут, произойдет возврат в магазин на страницу заказа. правильное поведение.

но если не дожидаться окончания таймера и нажать по ссылке, вот тогда у юзера сбрасывается сессия.

**Comment by Septdir** [comment]
Так и не поймал в итоге.
