### ISSUE TITLE
Авторизация или новый пользователь на этапе оформления заказа

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#48]
Обратил внимание, что если гостем добавить товар в корзину и пройти в нее, то вижу страницу оформления заказа:
<img width="1366" alt="Снимок экрана 2021-12-14 в 13 53 14" src="https://user-images.githubusercontent.com/3432048/145984815-46ceac4d-75a0-4430-b817-fdbfc38786e4.png">

но у меня уже есть юзер на сайте!
аа тут будет оформление заказа гостем + регистрация.
вот я ввел тот же email, что уже есть у юзера и оформляю заказ и получаю:

**У вас нет доступа к элементу. Пожалуйста, обратитесь к администрации сайта.**
и форму авторизации.

но юзер то не знает об этом и подумает о баге.
нужно вывести форму - авторизоваться или покупка без регистрации.

а если email такой уже есть, то не кидать на форму авторизации с текстом "у вас нет доступа", а вывесит сообщение: "такой email уже используется на сайте. авторизуйтесь или используйте др.email" и форма авторизации.

**Comment by Septdir** [comment]
Переключи оформление заказа гостем. тогда будет выводиться такое окно
