### ISSUE TITLE
Группы пользователей

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#49]
Предлагаю ввести группы пользователей. 

в  теории рассмотрим базовый маркетплейс, в рамках которого будут разные продавцы. 
например, магазин на 5 мастеров. но с каждым продавцом у владельца сайта свои договоренности.
механика: с каждой продажи часть денег идет продавцу, часть - магазину. 
насколько я понимаю, технически Mandarin поддерживает разделение платежей. для этого нужно написать платежный плагин.
теперь самое интересное. 
нужно сделать так, чтобы каждому продавцу выставлялись свои пропорции разделения платежей.

1 продавец - 50/50%
2 продавец - 20/80%
3 продавец - 40/60% 

первое значение  - вознаграждение магазину, второе значение - продавцу.
соответственно, нужно предусмотреть привязку к чему-то.

здесь я вижу два способа:
1. ввести в магазин группы пользователей.
можно создать разные группы и выбирать группу новым юзерам по умолчанию.  это может пригодиться как для модели маркетплейса, так и для накопительных скидок (siver - 5% скидка, gold - 10% скидка). эти скидки также отдельным плагином делаются, но нужно к чему-то привязываться.

2. привязываться к группам пользователей Joomla в платежном плагине и ручками выставлять пропорции разделения платежей. например, создать группы пользователей: партнер 1, партнер 2 и т.п. юзеров  назначить в эти группы.

**Comment by Sulpher** [comment]
в JoomShopping есть понятие группы пользователей и есть плагин для организации системы скидок.
юзер совершил покупок на 10 тыс. руб - назначаем его из группы registered в группу silver. и у него уже будет 5% скидка. купил на 50 тыс. - назначили в  группу gold, 10% скидка.
в настройках самой группы можно выставлять скидку. 

вот два сценария, для чего нужны пользовательские группы. как это пристроить в архитектуру Радикал, давайте подумаем.

**Comment by Septdir** [comment]
Кастомное решение для маркетплейса. Сделаем если потребуется.
