### ISSUE TITLE
Предусмотреть Sample data после установки

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#5]
В пост-установочном сообщении предложить юзеру установить демо-данные магазина.
пакет скачивать с внешнего сервера. SQL дамп + картинки.
буквально пара категорий и товаров, чтобы показать, как настроены мета-товары и др. поля.

**Comment by Septdir** [comment]
В ядре я бы не держал sample data. там есть cli для разрабов чтобы создавать тестовые данные.
