### ISSUE TITLE
RadicalMart Express: В сообщения приходит старый статус заказа

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#53]
RadicalMart Express

После смены статуса заказа платежным плагином статус заказа в админке меняется, но платежный плагин присылает неверную информацию о текущем статусе.
![2022-02-24_16-40-59](https://user-images.githubusercontent.com/17691519/155536026-1e14731d-299c-46e2-9d66-4a74d27be402.png)
![2022-02-24_16-40-33 (2)](https://user-images.githubusercontent.com/17691519/155536020-c9ef9781-38cb-4c75-a3fc-9571889b1689.png)

**Comment by Septdir** [comment]
Fix
