### ISSUE TITLE
RadicalMart Express: опечатка в сообщении о регистрации пользователя

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#54]
<img width="586" alt="Снимок экрана 2022-02-26 в 16 28 56" src="https://user-images.githubusercontent.com/3432048/155845107-289f71bb-bb0b-481f-b169-a4cadbccf573.png">

нужна запятая вместо битый символ.

и еще: пользователь не знал, что будет добавлена учетка на сайте. нужен чекбокс с принятием правил в форме заказа.
или от обратного: чекбокс "без регистрации" (если это вписывается в концепт)

**Comment by Septdir** [comment]
Битый символ исправлен.
По второму подумаем
