### ISSUE TITLE
Форма заявки в Radical Express

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#55]
Два момента:
1. сделать поле комментарий необязательным. туда нечего писать, если все устраивает
2. модальное окно закрывается, когда пытаешься выделить значение поля. например, браузер из буфера вставляет значение телефон или имя, я его хочу выделить и скопировать в буфер, но окно закрывается. проблема либо в uikit, либо в chrome.
 
<img width="662" alt="Снимок экрана 2022-02-26 в 20 38 281" src="https://user-images.githubusercontent.com/3432048/155854164-4b62702c-5daf-4dbb-8555-51b7b115147b.png">

**Comment by Septdir** [comment]
По первому все поля настраивается в настройках компонента.
Второе прсмотрим

**Comment by Septdir** [comment]
Баг с закрытием модалки не ловится. Как варинат могу сделать закрытье модалки. ТОЛЬКО при нажатии на крестик.

**Comment by Sulpher** [comment]
> Баг с закрытием модалки не ловится. Как варинат могу сделать закрытье модалки. ТОЛЬКО при нажатии на крестик.

ок, давай так.

**Comment by Septdir** [comment]
Войдет в сл. релиз
