### ISSUE TITLE
Добавить возможность открывать заказ без авторизации (по ключу)

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#56]
Кейс Радикал Экспресс

Первый раз захожу на сайт, делаю первый заказ, оплачиваю, заводится аккаунт, меня скрыто авторизовывают, заказ оплачивается, переходит на successUrl, все нормально.

Спустя какое-то время захожу (уже не авторизован). Ввожу те же данные при заказе. Зарегистрировать меня скорее всего уже не получается - аккаунт уже есть, авторизовать тоже. Заказ оплачиваю, перехожу на successUrl - доступ закрыт, я же не авторизован.

Покупатель скорее всего расстроен 😊

**Comment by Septdir** [comment]
Можно по пробовать сделать доступ к заказу по ссылке.

**Comment by Septdir** [comment]
Add in RM v1.1.0
