### ISSUE TITLE
Модель категорий

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#57]
Было бы неплохо добавить в объект категории модели Categories -  level и parent_id.

Parent_id нужен, чтобы построить дерево категорий.

Level пригодился бы при построении селекта для выбора категории (например, в провайдере для Yootheme Pro). Это не совсем критично, можно получить уровень прямым запросом в базу изначально в обход модели.

В общем смотри сам. Сейчас дерево категорий я составляю, получая объект каждой категории через модель Category. 

Я не в теме общей кухни и всех имеющихся разработок, но для меня было удобно то, что я написал выше.

**Comment by Septdir** [comment]
Добавил будет в сл версии.
Но я тут вспомнил что можно контролировать получаемые колонки путем передачи state('list.select')
