### ISSUE TITLE
Запоминать поля с адресом, сделать опцию адреса доставки и биллинга одинаковыми

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#6]
<img width="966" alt="Снимок экрана 2021-10-19 в 13 47 50" src="https://user-images.githubusercontent.com/3432048/137894862-7ad0d254-171e-460a-8aed-2d682f28a98b.png">

сделал заказ. делаю повторный заказ и  снова нужно вводить данные контактные. неудобно.
лучше такие поля забивать в профиль юзера после первого заказа.

второе: часто адрес выставления счета и адрес доставки совпадают. но иногда покупают подарок - не совпадает.
нужно добавить галочку "адрес выставления счета и адрес доставки одинаковые"

вот как сделано в др.магазине для примера:

checkout:
<img width="905" alt="Снимок экрана 2021-10-19 в 13 59 32" src="https://user-images.githubusercontent.com/3432048/137896929-a099c682-7dc1-4726-babc-c7eaa1732027.png">

редактирование адреса
<img width="933" alt="Снимок экрана 2021-10-19 в 13 59 42" src="https://user-images.githubusercontent.com/3432048/137896945-8a142a44-9d31-459f-9b96-da1392bfee26.png">
:

**Comment by Septdir** [comment]
Автозаполнение контактный сделаем. А вот один адрес для доставки и биллинга, тут вопрос к плагинам доставки ибо если там будет просто карта не факт что выйдет выдернуть от туда нужные поля.
