### ISSUE TITLE
Вернуть ссылку для принудительного перехода по ссылке

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#60]
<img width="969" alt="Снимок экрана 2022-04-16 в 14 05 33" src="https://user-images.githubusercontent.com/3432048/163676053-4cc6b59a-c4c4-43d3-a102-65350e5d708d.png">
 
почему-то здесь убрали ссылку на принудительный переход. я вот не хочу ждать 9 секунд.. раздражает такое

всегда нажимаю, когда есть возможность

**Comment by Septdir** [comment]
А какой плагин оплаты. Просто у меня все норм.
![изображение](https://user-images.githubusercontent.com/18382023/163813207-38ab8433-de2f-4f95-8633-9b563db7d92c.png)

**Comment by b2z** [comment]
@Septdir ссылка в плагине формируется? Вроде раньше у нас работало, а тут вдруг пропала.

**Comment by Septdir** [comment]
Саму ссылку на заказ формирует компонент. Однако плагин может заменять этот макет.

**Comment by b2z** [comment]
@Septdir макетов у нас нет в плагинах.
