### ISSUE TITLE
Пропущена локализация плагина рассылок

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#61]
<img width="1053" alt="Снимок экрана 2022-04-16 в 14 02 39" src="https://user-images.githubusercontent.com/3432048/163676708-20665b2a-4fa7-4439-b6a5-1c5d7895e1b4.png">

пропущена локализация плагина рассылок.
версия плагина: 1.1.0

COM_RADICALMART_PARAMS_MESSAGES

внутри все ок:
<img width="1372" alt="Снимок экрана 2022-04-16 в 16 27 42" src="https://user-images.githubusercontent.com/3432048/163676756-497e88da-2ec4-49ac-bc6b-251c29ff9356.png">

тестирую на RadicalMart версия: 0.4.1

**Comment by Septdir** [comment]
Уже пофикшено выйдет со следующей версий
