### ISSUE TITLE
Добавить классы label статусам заказов

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#63]
Сделать как в экспресс.
сейчас невыразительно:
<img width="754" alt="Снимок экрана 2022-05-06 в 12 04 09" src="https://user-images.githubusercontent.com/3432048/167144961-e42b8242-1d7a-4fc1-bb68-f89ea2dc9ac3.png">

**Comment by Septdir** [comment]
Войдет в сл. версию
