### ISSUE TITLE
Добавить параметр класса полю Products

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#64]
Для облегчения интеграции поля Products в сторонние плагины и модули было бы неплохо добавить параметр `class`, чтобы изменить дефолтный класс `input-xxlarge`.

Кейс - поле товара для связанных товаров

![2022-05-14_10-53-44](https://user-images.githubusercontent.com/17691519/168417913-c17bffa3-cc97-4b2d-8304-27b50f558bce.png).

**Comment by Septdir** [comment]
Готово
