### ISSUE TITLE
Опечатка в статусе Completed

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#67]
иду в статусы. список статусов - все ок. открываю любой статус и вижу:
COM_RADICALMART_STATUS_COMPLETED

так и должно быть?

<img width="1274" alt="Снимок экрана 2022-08-01 в 12 12 40" src="https://user-images.githubusercontent.com/3432048/182115250-5d4c45e8-8552-4f77-98fb-7f3cb1739039.png">

у статуса завершен в сообщении это:
COM_RADICALMART_STATUS_CANCELED_MESSAGE

(отменен)

**Comment by Septdir** [comment]
Done. Войдет в 0.7.0
Так же и цвета поправил
