### ISSUE TITLE
Не обновляются данные на странице Личные данные

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#68]
пункт меню Личные данные

обновляю имя, нажимаю на обновить. изменения не вносятся. остается прежнее имя.

при каждом новом заказе контактные данные старые.
страница контактные данные. поменял имя и фамилию. но в заказе все равно старые данные (см. выше скриншот)

RadicalMart Версия: 0.5.1
Joomla 4.1.5

**Comment by Septdir** [comment]
Done.
Войдет в 0.7.0
