### ISSUE TITLE
Редактирование профиля пользователя - обязательные поля

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#7]
меняю данные в профиле юзера. 
сменил имя, email, телефон не трогал. в итоге ошибка.
<img width="704" alt="Снимок экрана 2021-10-19 в 14 08 02" src="https://user-images.githubusercontent.com/3432048/137898107-a4f65c8b-aedd-475a-b7e9-bf151f200470.png">

получается, что при редактировании профиля, нужно все обязательные поля редактировать. а если я хочу оставить прежнее значение - нужно дублировать его.

**Comment by Septdir** [comment]
Для разделения есть технические причины. Ну а если хочется все одном, то это лишь верстка.
