### ISSUE TITLE
Ряд замечаний по RadicalExpress

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#71]
1. модальное окно по нажатию на кнопку оплатить: 
<img width="681" alt="Снимок экрана 2022-10-27 в 23 26 43" src="https://user-images.githubusercontent.com/3432048/198827679-6eaf673b-a42c-4b6a-b20e-c96a51da7b8f.png">

обрати внимание на оформление кнопок в фоне картинки на заднем плане. нужно класс добавить кнопке, чтобы было единоообразие стилей Uikit. или в настройках магазина опционального указать.

```
<a onclick="RadicalMartExpress().createOrder('radicalmart_express_checkout')" style="display: inline-block; padding: 0 30px; vertical-align: middle; font-size: 16px; line-height: 40px; background-color: #1e87f0; color: #fff; cursor: pointer; text-decoration: none;">Оплатить  </a>
```

2. Плагин шорткод кнопки. нужна возможность кастомного текста для кнопки. проблема решилалсь через элемент билдера, но если делать задел под  др фреймворки, лучше заложить в плагин редактора такую возможность тоже.

3. выбор кол-ва товара
<img width="588" alt="Снимок экрана 2022-10-27 в 22 52 05" src="https://user-images.githubusercontent.com/3432048/198827772-eea75104-c969-4350-a2a3-a35933327454.png">
нажимаю на плюсик и в консоли:

```
Uncaught ReferenceError: RadicalMartFieldQuantity is not defined
    onclick https://сайт.ru/kursy/webinar.html:1
```
Joomla 4, март экпресс 1.1.0. сайт на билдере последнем и включен BS5.

4. форма заявки. нужен новый параметр чекбокса согласия с правилами. это крайне важно. ссылку на правила и кастомный текст - либо через переопределение языковой константы, либо в настройках магазина.

5. валюта магазина. указываю USD. но в редактировании товара и в инвойсе на фронте все равно рубль выводится:
![2022-10-29 14 09 21](https://user-images.githubusercontent.com/3432048/198828134-05ef4d73-1420-4127-a24e-1a1fc3e22150.jpg)

![2022-10-29 14 09 31](https://user-images.githubusercontent.com/3432048/198828145-b8619b3b-8ddb-4492-bc9b-476dcf14019e.jpg)

![2022-10-29 14 09 15-11](https://user-images.githubusercontent.com/3432048/198828267-8299ba8b-58ab-4523-ac35-ab183049e30e.jpg)

еще обрати внимание: в инвойсе знак валюты после цены. в магазине указано ДО

ПОСЛЕ ОПЛАТЫ:
5. существенный момент: если нажимаю на этапе платежного плагина "отмена", то осуществляется возврат обратно:
<img width="823" alt="Снимок экрана 2022-10-29 в 12 42 28" src="https://user-images.githubusercontent.com/3432048/198827917-2cc0f428-fc07-4b17-b416-4097b48fb62a.png">

сообщение некорректное: благодарим вас за оплату заказа. это при отмене операции.
и когда возвращаемся, то страница инвойса - статус у заказа:  НОВЫЙ. по логике, должен быть **_отменен_**.

отсюда просится в настройках магазина параметр для выставления статусов при разных операциях.

7. в настройках товара есть редирект на страницу:
<img width="1354" alt="Снимок экрана 2022-10-29 в 13 23 56" src="https://user-images.githubusercontent.com/3432048/198828026-b9e275b4-f7e4-4b6d-a19e-6c46794e4352.png">
после успешной оплаты должно перекинуть на страницу com_content, указанную в настройках магазина, но по факту, кидает на страницу инвойса.

**Comment by Septdir** [comment]
Fix maybe in RME 2.0
