### ISSUE TITLE
RadicalMart Предупреждение в корзине

### ISSUE THREAD

**Issue by fiction13** [RadicalMart/Bug-Tracker#72]
Если перейти из корзины на страницу оплаты, а потом дважды вернуться назад в браузере, получаем 

`Warning: Attempt to read property "productsErrors" on bool in /var/www/fiction/www/j4.fictionlabs.ru/components/com_radicalmart/views/cart/view.html.php on line 122`

![2022-11-14_12-46-31](https://user-images.githubusercontent.com/17691519/201630773-7ee3c0f7-ca32-4f81-bea6-4b7c6b634abc.png)

**Comment by cave2006** [comment]
Также наблюдается ошибка при удалении товара из корзины

https://user-images.githubusercontent.com/8674347/201913012-114c0226-0354-45f8-836c-2347d7c2c813.mp4

**Comment by Septdir** [comment]
Fix in RM 1.0
