### ISSUE TITLE
Исправить роутер в RadicalMart Express

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#73]
беседа: https://t.me/c/1644266252/9414
 нет обработки ЧПУ в админке. 
поле, куда кидать после оплаты:
index.php?option=com_content&view=article&id=572&catid=62

туда и кидает и на фронте нет ЧПУ. я знаю, что это проблема. но она решаема. 

решение:
----
...метод link

`Route::link('site', SWJProjectsHelperRoute::getDownloadRoute(null, null, $item->element))`
 

1. 

2. здесь ссылка на товар такая:
<img width="674" alt="Снимок экрана 2023-01-06 в 21 15 44" src="https://user-images.githubusercontent.com/3432048/211075400-98f73789-c6ea-4027-a72a-ff68a3a7d447.png">

https://сайт.ru/?view=article&id=672&catid=362з

хотя в настройках товара обычная не ЧПУ ссылка. тут роутер неправильно отрабатывает

**Comment by Septdir** [comment]
Заменено и исправлено в RME 2.0
