### ISSUE TITLE
Нотисы на фронте RadicalMart Express

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#74]
на фронте пункт меню экспресса. J4, php 7.4, экспресс последняя версия.

Notice: Undefined property: stdClass::$currency in /var/www/.ru/components/com_radicalmart_express/models/orders.php on line 170

Notice: Undefined property: stdClass::$shipping in /var/www/.ru/components/com_radicalmart_express/views/orders/tmpl/default.php on line 69

валюта магазина - USD.

**Comment by Septdir** [comment]
Fix in RME 2.0
