### ISSUE TITLE
Опечатка в экпрессе  с правилами

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#75]
`Необходимо правильно заполнить Принимаю правила Пожалуйста, выберите значение`

переименовать так:

`Необходимо правильно заполнить поле «Принимаю правила». Пожалуйста, выберите значение`

из коробки.

**Comment by Septdir** [comment]
Заменено на стандартную Joomla валидацию в RME 2.0.
Так что и константы тоже родные.
