### ISSUE TITLE
Экспресс: доп.поле для вывода ниже кнопки "купить" на фронте

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#76]
вот что подумал: нужно ниже кнопки оплатить вставить информацию о способе оплаты: лого, текст и ссылка на статью об оплате. 
предлагаю добавить такую фичу - поле в настройках экспресс. чтобы юзерам не пришлось  переопределять шаблон. а так шорткодом вставить можно будет что угодно через Revars.
<img width="572" alt="Снимок экрана 2023-01-06 в 18 10 29" src="https://user-images.githubusercontent.com/3432048/211076053-98695101-8c85-4cd3-8443-6693df5a24a0.png">

**Comment by Septdir** [comment]
Добавлено в RME 2.0
