### ISSUE TITLE
Экспресс - нет ссылки на товар если заказ не оплачен

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#79]
экспресс. заказ. статус "новый". нет ссылки на товар.
<img width="1103" alt="Снимок экрана 2023-01-10 в 12 30 31" src="https://user-images.githubusercontent.com/3432048/211514275-b6d95cf3-6633-4a67-b2c6-b1aff2b75582.png">

заказ. статус оплачен. ссылка на товар есть:
<img width="966" alt="Снимок экрана 2023-01-10 в 12 31 36" src="https://user-images.githubusercontent.com/3432048/211514381-19fafde5-5095-484a-940a-c9451475b703.png">

это же касается и списка заказорв

**Comment by Septdir** [comment]
Ссылки на товар появиться в RM 2.0.
А ссылки после оплаты перейдут в отдельные решения
