### ISSUE TITLE
Редактирование профиля пользователя - вывод модуля со своими пунктами меню

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#8]
В левом сайдбаре есть два пункта:
- заказы
- личные данные

<img width="268" alt="Снимок экрана 2021-10-19 в 14 14 49" src="https://user-images.githubusercontent.com/3432048/137898856-0cdf83be-23a7-4149-8c6b-526276984faf.png">
может понадобиться изменить их, порядок, добавить новые пункты.
предлагаю добавить опцию: использовать внешний модуль  меню.
если отключено - выводятся эти два пункта по умолчанию. 
если включено - нужно выбрать mod_menu со своим набором пунктов меню.

**Comment by Septdir** [comment]
Для разработчиков там есть триггер.
`onRadicalMartAccountMenu`
доступный для групп `system` `radicalmart` и `content`
Но насчет меню подумаем
