### ISSUE TITLE
Express: валидация в uikit шаблоне не родная

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#80]
Версия: 1.1.2-dev
вижу в настройках режим Uikit. да/нет. включено да.

но в модалке валидация не юикитовская.
<img width="573" alt="Снимок экрана 2023-01-10 в 12 34 57" src="https://user-images.githubusercontent.com/3432048/211514892-df8ec442-6ccb-47e6-b2d3-38d9218bd976.png">

**Comment by Sulpher** [comment]
так красивее будет:
<img width="460" alt="Снимок экрана 2023-01-10 в 12 36 28" src="https://user-images.githubusercontent.com/3432048/211515224-bead7ad8-9827-40c1-ac05-c15cf7ce31c9.png">

**Comment by Septdir** [comment]
Заменено на родную валидацию Joomla в RME 2.0
