### ISSUE TITLE
[RM] При создании товара выбирать по умолчанию значение сантиметр

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#84]
<img width="782" alt="Снимок экрана 2023-02-05 в 22 55 48" src="https://user-images.githubusercontent.com/3432048/216841722-f3ff48e0-dd85-410f-b5ad-cac079cc54a6.png">

по умолчанию это метр. у товаров, скорее, см. сделать по умолчанию

**Comment by cave2006** [comment]
Чтобы определить какие нужны единицы измерения для доставки, то надо смотреть популярные сервисы доставки. Что они там принимают, чтоб не конвертить потом десять раз. На сколько я видел. везде метры приняты. Поэтому лучше отклонить.

**Comment by progreccor** [comment]
но с другой стороны на wildberries и на ozon - везде см

**Comment by Sulpher** [comment]
> Чтобы определить какие нужны единицы измерения для доставки, то надо смотреть популярные сервисы доставки. Что они там принимают, чтоб не конвертить потом десять раз. На сколько я видел. везде метры приняты. Поэтому лучше отклонить.

разумная мысль - уточнить стандарты у сервисов доставки.
@progreccor  @Septdir хорошо бы задать вопрос ApiShip, если есть контакт

**Comment by Sulpher** [comment]
но если подходить с точки зрения удобства заполнения, давайте выберем более распространненную единицу.
вот я заполнял кучу товаров из разряда copy/paste, поэтому лишние действия и клики критичны. постоянно приходилось выбрать см вместо м. и, подчеркну - в большинстве товаров это именно см. одежда, обувь, габариты коробок.

**Comment by progreccor** [comment]
надо изучить вопрос
при поверхностном изучении - маркетплейсы ставят см

**Comment by Georgiy163** [comment]
Считаю нужным сделать мм по умолчанию. Озон нам не пример

**Comment by Georgiy163** [comment]
Все всю жизнь привыкли к мм кто немного в инженерии работает

**Comment by Georgiy163** [comment]
Правда у меня вообще делема у нас кондиционер состоит из двух раздельных блоков как их складывать?

**Comment by Septdir** [comment]
Установлены cm
