### ISSUE TITLE
Не влезает по ширине элемент при редактировании поля

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#85]
Элемент "Значения" при редактировании поля "Стандарт - чекбокс" не влезает по ширине (появляется горизонтальный скролл). Экран 2560х1600, масштаб windows - 150%.
![issue](https://user-images.githubusercontent.com/88541095/217508091-e051bf3a-0e43-4b5a-ab4e-ad5a7aa5bc4b.jpg)

**Comment by Septdir** [comment]
Это к сожалению не поправить, можно было бы заменить на другой макет subform, но он куда менее удобен чем таблица.
