### ISSUE TITLE
Символ "&" в значении поля вызывает ошибку.

### ISSUE THREAD

**Issue by mius-it** [RadicalMart/Bug-Tracker#86]
Поле "Стандарт - чекбокс". Значение, содержащее символ "&" при редактировании товара приводит к ошибке, а вместо текста выводится алиас значения поля.

<img width="1231" alt="issue2-1" src="https://user-images.githubusercontent.com/88541095/217509600-00b595dc-4a13-4346-a6ba-c1f0298dba8a.png">
<img width="1035" alt="issue2-2" src="https://user-images.githubusercontent.com/88541095/217509605-a404dd5e-2157-4aa3-b655-8fa6d79b9112.png">

**Comment by Septdir** [comment]
FIX in plg_radicalmart_fields_standard 1.2.2
