### ISSUE TITLE
Макет страницы "мои заказы"

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#9]
Сейчас выглядит так
<img width="692" alt="Снимок экрана 2021-10-19 в 14 16 54" src="https://user-images.githubusercontent.com/3432048/137899242-6d5e6ab3-c544-47e5-b949-a92f93f65c9e.png">
не компактно.
нужно либо в сплойлер обернуть и раскрывать детали по клику, либо сделать так:
<img width="889" alt="Снимок экрана 2021-10-19 в 14 17 23" src="https://user-images.githubusercontent.com/3432048/137899311-c370ee75-65b6-4bf9-b63b-51ef56151723.png">

довольно хорошо закомпоновано и не занимает много места.
да, еще можно мини-эскизы товаров вывести слева, но это необязательно.

**Comment by Sulpher** [comment]
как раз можно брать эскизы для админки (параметр `Высота картинки в панели управления`) и выводить их тут в списке заказа.

**Comment by Septdir** [comment]
Артем делал для Svarpost разваривающиеся заказы, так что вопрос верски.
