### ISSUE TITLE
Состояния для заказов в RM и RME

### ISSUE THREAD

**Issue by nevigen** [RadicalMart/Bug-Tracker#92]
удаление заказов зло. это и статистика и учет, и куча всего потом.
единственное чем они могут досаждать это показом менеджеру.
если в списке заказов админки мешают лишние/брошенные заказы, лучше решать вопрос их скрытием. 
например опубликовано/неопубликовано. 
или метку в корзине, как у материалов.
этот же принцип можно использовать и в кабинете клиента, если он хочет удалить (а не просто отменить) заказ.

**Comment by Septdir** [comment]
Добавить состояния 
* Опубликован
* В архиве
* В корзине

В базе по умолчанию state = 1
