### ISSUE TITLE
Вынести список позиций в аккордеон

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#94]
<img width="900" alt="Снимок экрана 2023-02-21 в 15 27 48" src="https://user-images.githubusercontent.com/3432048/220345346-7f390a66-7dd3-4333-8e60-ca73323ddf17.png">

в который раз  ловлю себя на мысли, что список позиций мешает понять, модуль включен или нет. может в раскрывающийся список вынести? 
вывести первые 3 примера и далее спойлер - см.все позиции

**Comment by Septdir** [comment]
![изображение](https://user-images.githubusercontent.com/18382023/220375777-09f983f8-8957-4d7f-8ca2-00eefa0f5182.png)
