### ISSUE TITLE
Выводить содержимое вкладки поля  в одну колонку

### ISSUE THREAD

**Issue by Sulpher** [RadicalMart/Bug-Tracker#95]
записал видос, показал недостатки архитектуры RM и Joomla 4 с точки зрения пользователя. 5 мин.

https://t.me/c/1644266252/12582

кратко:
- Выводить содержимое вкладки поля  в одну колонку
- кнопка редактировать - переименовать в Ред. или просто оставить иконку редактирования

**Comment by Septdir** [comment]
Если выводить содержимое вклади в одну колонку, то у тебя селект будет во весь экран в итоге на экране поместится крайне мало полей

**Comment by Sulpher** [comment]
вот как выглядит плагин "связанные товары" @fiction13

совершенно непонятно, какие значения подтянуты.
<img width="1400" alt="Снимок экрана 2023-02-21 в 15 39 01" src="https://user-images.githubusercontent.com/3432048/220347231-0b8f97bb-0dca-4fd0-964a-5ff64a0b8e6b.png">

это реально неудобно

**Comment by Septdir** [comment]
Это вопрос к @fiction13 потому что поле умеет только иконки выводить.
![изображение](https://user-images.githubusercontent.com/18382023/220347714-9fa097f8-02f6-4feb-96b1-4a9361110329.png)

**Comment by Sulpher** [comment]
ну это вопрос к общей архитектуре.
товарам в маркетплейсах  делают  длинные названия, пихая ключевики. и нужно иметь возможность прочитать название.
для этого ширина в одну колонку нужна и поле очень широкое, значеие которого будет хорошо смотреться.

**Comment by Sulpher** [comment]
пример: 
<img width="882" alt="Снимок экрана 2023-02-21 в 15 45 40" src="https://user-images.githubusercontent.com/3432048/220348362-730070af-d57c-4efc-b060-54dc14e8a47f.png">

и люди будут такие названия делать

**Comment by Septdir** [comment]
Add to RM 1.1
